PROC Wait(BYTE frames)
  BYTE RTCLOK=$14
  frames==+RTCLOK
  WHILE frames#RTCLOK DO OD
RETURN

PROC Main()
  BYTE
    i,n=[3],
    CH=$02FC ;Internal hardware value for last key pressed

  PrintF("Press any key to hear %B bells...",n)
  DO UNTIL CH#$FF OD
  CH=$FF

  FOR i=1 TO n
  DO
    Put(253) ;buzzer
    Wait(20)
  OD
  Wait(100)
RETURN
