PROC Save(CHAR ARRAY text)
  BYTE dev=[1]

  Close(dev)
  Open(dev,"C:",8,128)
  PrintE("Saving started...")
  PrintF("Saving text: ""%S""%E",text)
  PrintD(dev,text)
  Close(dev)
  PrintE("Saving finished.")
RETURN

PROC Load()
  CHAR ARRAY result(255)
  BYTE dev=[1]

  Close(dev)
  Open(dev,"C:",4,128)
  PrintE("Loading started...")
  WHILE Eof(dev)=0
  DO
    InputSD(dev,result)
    PrintF("Loading text: ""%S""%E",result)
  OD
  Close(dev)
  PrintE("Loading finished.")
RETURN

PROC Main()
  BYTE CH=$02FC ;Internal hardware value for last key pressed

  PrintE("Press any key to save a file on tape.")
  Save("Atari Action!")

  PutE()
  PrintE("Rewind the tape and press any key to load previously saved file from tape.")
  Load()
RETURN
