PROC Main()
  BYTE
    CH=$02FC, ;Internal hardware value for last key pressed
    PALNTSC=$D014 ;To check if PAL or NTSC system is used

  Graphics(8+16) ;Graphics 320x192 with 2 luminances
  IF PALNTSC=15 THEN
    SetColor(1,4,6) ;Red color for NTSC
    SetColor(2,4,15)
  ELSE
    SetColor(1,2,6) ;Red color for PAL
    SetColor(2,2,15)
  FI
  Color=1
  Plot(100,100)

  DO UNTIL CH#$FF OD
  CH=$FF
RETURN
