PROC Reverse(CHAR ARRAY src,dst)
  BYTE i,j

  i=1 j=src(0) dst(0)=j
  WHILE j>0
  DO
    dst(j)=src(i)
    i==+1 j==-1
  OD
RETURN

PROC Test(CHAR ARRAY src)
  CHAR ARRAY dst(40)

  Reverse(src,dst)
  PrintF("'%S' -> '%S'%E",src,dst)
RETURN

PROC Main()
  Test("Hello World!")
  Test("123456789")
  Test("!noitcA iratA")
RETURN
