BYTE FUNC IsHexWithoutDigits(INT x)
  DO
    IF x MOD 16<10 THEN
      RETURN (0)
    FI
    x==/16
  UNTIL x=0
  OD
RETURN (1)

PROC Main()
  INT i,count,min=[0],max=[499]

  count=0
  FOR i=min TO max
  DO
    IF IsHexWithoutDigits(i) THEN
      PrintI(i) Put(32)
      count==+1
    FI
  OD
  PrintF("%E%EFound %I numbers between %I and %I",count,min,max)
RETURN
