PROC Wait(BYTE frames)
  BYTE RTCLOK=$14
  frames==+RTCLOK
  WHILE frames#RTCLOK DO OD
RETURN

PROC Main()
  BYTE CRSINH=$02F0 ;Controls visibility of cursor

  Print("Hiding the cursor...")
  Wait(50)
  CRSINH=1 PutE() ;put the new line character to force hide the cursor
  Wait(50)

  Print("Showing the cursor...")
  Wait(50)
  CRSINH=0 PutE() ;put the new line character to force show the cursor
  Wait(50)
RETURN
