(defun pascal (r)
  (let ((out ""))
    (dotimes (i r)
      (let ((c 1))
        (dotimes (k (+ i 1))
          (setq out (concat out  (format "%d " c)))
          (setq c (/ (* c (- i k))
                     (+ k 1))))
        (setq out (concat out "\n"))))
    out))
