...
  val tenants = List("Baker", "Cooper", "Fletcher", "Miller", "Smith", "Rollo")
...
  val predicates =
    List((perm: Map[String, Int]) => !(perm("Baker")==floors.size)
...
        ,(perm: Map[String, Int]) => !(perm("Rollo")==floors.size || perm("Rollo")==3 || perm("Rollo")==4)
        ,(perm: Map[String, Int]) => !(perm("Rollo")>perm("Smith"))
        ,(perm: Map[String, Int]) => !(perm("Rollo")<perm("Fletcher"))
        )
...
