INCLUDE "H6:SIEVE.ACT"

BYTE FUNC IsPrimeWord(CHAR ARRAY word BYTE ARRAY primes)
  BYTE i,c

  FOR i=1 TO word(0)
  DO
    c=word(i)
    IF primes(c)=0 THEN
      RETURN (0)
    FI
  OD
RETURN (1)

PROC FindPrimeWords(CHAR ARRAY fname BYTE ARRAY primes)
  CHAR ARRAY line(256)
  CHAR ARRAY tmp(256)
  BYTE pos,dev=[1]

  pos=2
  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    IF IsPrimeWord(line,primes) THEN
      IF pos+line(0)>=39 THEN
        PutE() pos=2
      FI
      Print(line) Put(32)
      pos==+line(0)+1
    FI
  OD
  Close(dev)
RETURN

PROC Main()
  DEFINE MAX="128"
  BYTE ARRAY primes(MAX+1)
  CHAR ARRAY fname="H6:UNIXDICT.TXT"

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAX+1)
  FindPrimeWords(fname,primes)
RETURN
