(defun deg->rad (x) (* x (/ pi 180)))
(defun rad->deg (x) (* x (/ 180 pi)))

(mapc (lambda (x) (format t "~s => ~s~%" x (eval x)))
  '((sin (/ pi 4))
    (sin (deg->rad 45))
    (cos (/ pi 6))
    (cos (deg->rad 30))
    (tan (/ pi 3))
    (tan (deg->rad 60))
    (asin 1)
    (rad->deg (asin 1))
    (acos 1/2)
    (rad->deg (acos 1/2))
    (atan 15)
    (rad->deg (atan 15))))
