PROC DrawRectangles()
  BYTE i,x1,y1,x2,y2

  x1=40 y1=8 x2=119 y2=87
  FOR i=1 TO 20
  DO
    Plot(x1,y1)
    DrawTo(x2,y1)
    DrawTo(x2,y2)
    DrawTo(x1,y2)
    DrawTo(x1,y1)
    x1==+2 y1==+2
    x2==-2 y2==-2
  OD
RETURN

PROC Main()
  BYTE CH=$02FC
  BYTE hue,lum

  Graphics(7+16)
  Color=1
  DO
    IF Color=1 THEN
      Color=2
    ELSE
      Color=1
    FI
    hue=Rand(16)
    lum=Rand(8)*2
    SetColor(Color-1,hue,lum)
    DrawRectangles()
  UNTIL CH#$FF
  OD
  CH=$FF
RETURN
