HAI 1.4

CAN HAS STRING?

HOW IZ I REVERSE YR S
    I HAS A L ITZ STRING IZ LEN YR S MKAY
    I HAS A OUTPUT ITZ ""
    IM IN YR LOOP UPPIN YR N TIL BOTH SAEM N AN L
        I HAS A C ITZ STRING IZ AT YR S AN YR DIFF OF L AN N MKAY
        OUTPUT R SMOOSH OUTPUT C MKAY
    IM OUTTA YR LOOP
    FOUND YR SMOOSH OUTPUT STRING IZ AT YR S AN YR 0 MKAY MKAY
IF U SAY SO

VISIBLE I IZ REVERSE YR "ASDF" MKAY

KTHXBYE
