;;; find idoneal numbers - numbers that cannot be written as ab + bc + ac
;;;                        where 0 < a < b < c
;;; there are 65 known idoneal numbers

PROC Main()
  CARD count, maxCount, n, a, b, c, ab, sum
  BYTE idoneal

  count = 0 maxCount = 65
  n = 0
  WHILE count < maxCount DO
    n  ==+ 1
    idoneal = 1
    a = 1
    WHILE ( a + 2 ) < n AND idoneal = 1 DO
      b = a + 1
      DO
        ab  = a * b
        sum = 0
        IF ab < n THEN
          c   = ( n - ab ) / ( a + b )
          sum = ab + ( c * ( b + a ) )
          IF c > b AND sum = n THEN idoneal = 0 FI
          b ==+ 1
        FI
      UNTIL sum > n OR idoneal = 0 OR ab >= n
      OD
      a ==+ 1
    OD
    IF idoneal THEN
      Put(' )
      IF n <   10 THEN Put(' ) FI
      IF n <  100 THEN Put(' ) FI
      IF n < 1000 THEN Put(' ) FI
      PrintC( n )
      count ==+ 1
      IF count MOD 13 = 0 THEN PutE() FI
    FI
  OD

RETURN
