INCLUDE "D2:SORT.ACT" ;from the Action! Tool Kit

INT FUNC Power(INT a,b)
  INT res,i

  res=1
  FOR i=1 TO b
  DO
    res==*a
  OD
RETURN (res)

BYTE FUNC Contains(INT ARRAY a INT count,x)
  INT i

  FOR i=0 TO count-1
  DO
    IF a(i)=x THEN
      RETURN (1)
    FI
  OD
RETURN (0)

PROC Main()
  INT ARRAY a(100)
  INT i,j,x,count

  Put(125) PutE() ;clear the screen

  count=0
  FOR i=2 TO 5
  DO
    FOR j=2 TO 5
    DO
      x=Power(i,j)
      IF Contains(a,count,x)=0 THEN
        a(count)=x
        count==+1
      FI
    OD
  OD
  SortI(a,count,0)
  FOR i=0 TO count-1
  DO
    PrintI(a(i)) Put(32)
  OD
RETURN
