BYTE FUNC IsPrime(CARD a)
  CARD i

  IF a<=1 THEN
    RETURN (0)
  FI

  FOR i=2 TO a/2
  DO
    IF a MOD i=0 THEN
      RETURN (0)
    FI
  OD
RETURN (1)

PROC Test(CARD a)
  IF IsPrime(a) THEN
    PrintF("%I is prime%E",a)
  ELSE
    PrintF("%I is not prime%E",a)
  FI
RETURN

PROC Main()
  Test(13)
  Test(997)
  Test(1)
  Test(6)
  Test(120)
  Test(0)
RETURN
