PROC Draw(INT x0 BYTE y0,depth)
  BYTE i,x,y,size

  size=1 LSH depth

  FOR y=0 TO size-1
  DO
    FOR x=0 TO size-1
    DO
      IF (x&y)=0 THEN
        Plot(x0+x,y0+y)
      FI
    OD
  OD
RETURN

PROC Main()
  BYTE CH=$02FC,COLOR1=$02C5,COLOR2=$02C6

  Graphics(8+16)
  Color=1
  COLOR1=$0C
  COLOR2=$02

  Draw(96,32,7)

  DO UNTIL CH#$FF OD
  CH=$FF
RETURN
