"
accost:        acs        cot
accuse:        acs        cue
afield:        ail        fed
agleam:        ala        gem
alcott:        act        lot
allele:        all        lee
allied:        ale        lid
alpert:        apr        let
apport:        apr        pot
assist:        ass        sit
battle:        btl        ate
blaine:        ban        lie
brenda:        bed        rna
choose:        cos        hoe
choosy:        cos        hoy
claire:        car        lie
effete:        eft        fee
fabric:        fbi        arc
fealty:        fat        ely
fluent:        fun        let
friend:        fin        red
george:        gog        ere
inroad:        ira        nod
israel:        ire        sal
jaunty:        jut        any
joanne:        jan        one
lounge:        lug        one
oriole:        oil        roe
oswald:        owl        sad
parrot:        pro        art
peoria:        poi        era
pierre:        per        ire
poodle:        pol        ode
pounce:        puc        one
racial:        rca        ail
realty:        rat        ely
sordid:        sri        odd
sprain:        sri        pan
strain:        sri        tan
strait:        sri        tat
sturdy:        sud        try
sweaty:        set        way
tattle:        ttl        ate
though:        tog        huh
triode:        tid        roe
triune:        tin        rue
troupe:        top        rue
truant:        tun        rat
twirly:        til        wry
ambient:       abet       min
annette:       ante       net
ariadne:       aide       ran
collude:       clue       old
forwent:       fret       own
spatial:       sail       pta
theorem:       term       hoe
throaty:       tray       hot
calliope:      clip       aloe"
