BYTE FUNC GetLength(CHAR ARRAY s BYTE start)
  BYTE ARRAY tab(256)
  BYTE i
  CHAR c

  Zero(tab,256)
  i=start
  WHILE i<=s(0)
  DO
    c=s(i)
    tab(c)==+1
    IF tab(c)>1 THEN
      EXIT
    FI
    i==+1
  OD
RETURN (i-start)

PROC LongestSubstrings(CHAR ARRAY s)
  CHAR ARRAY tmp(256)
  BYTE count,maxLen,i,len

  IF s(0)=0 THEN
    RETURN
  FI

  i=1 maxLen=0
  FOR i=1 TO s(0)
  DO
    len=GetLength(s,i)
    IF len>maxLen THEN
      maxLen=len
    FI
  OD

  count=0
  FOR i=1 TO s(0)
  DO
    len=GetLength(s,i)
    IF len=maxLen THEN
      IF count>0 THEN
        Print(", ")
      FI
      SCopyS(tmp,s,i,i+maxlen-1)
      PrintF("""%S""",tmp)
      count==+1
    FI
  OD
RETURN

PROC Test(CHAR ARRAY s)
  PrintF("Input: ""%S""%E",s)
  Print("Result: [")
  LongestSubstrings(s)
  PrintE("]") PutE()
RETURN

PROC Main()
  Test("xyzyabcybdfd")
  Test("xyzyab")
  Test("zzzzz")
  Test("a")
  Test("thisisastringtest")
  Test("")
RETURN
