HAI 1.3

I HAS A s ITZ A BUKKIT
s HAS A SRS 0 ITZ 1
s HAS A SRS 1 ITZ 2
s HAS A SRS 2 ITZ 2
s HAS A SRS 3 ITZ 3
s HAS A SRS 4 ITZ 4
s HAS A SRS 5 ITZ 4
s HAS A SRS 6 ITZ 5

IM IN YR LOOP UPPIN YR i TIL BOTH SAEM i AN 7
    I HAS A prev
    I HAS A curr ITZ s'Z SRS i
    BOTH OF DIFFRINT i AN SMALLR OF i AN 0 AN BOTH SAEM prev AN curr, O RLY?
        YA RLY, VISIBLE i
    OIC
    prev R curr
IM OUTTA YR LOOP

KTHXBYE
