sequence = %w(
  CGTAAAAAATTACAACGTCCTTTGGCTATCTCTTAAACTCCTGCTAAATG
  CTCGTGCTTTCCAATTATGTAAGCGTTCCGAGACGGGGTGGTCGATTCTG
  AGGACAAAGGTCAAGATGGAGCGCATCGAACGCAATAAGGATCATTTGAT
  GGGACGTTTCGTCGACAAAGTCTTGTTTCGAGAGTAACGGCTACCGTCTT
  CGATTCTGCTTATAACACTATGTTCTTATGAAATGGATGTTCTGAGTTGG
  TCAGTCCCAATGTGCGGGGTTTCTTTTAGTACGTCGGGAGTGGTATTATA
  TTTAATTTTTCTATATAGCGATCTGTATTTAAGCAATTCATTTAGGTTAT
  CGCCGCGATGCTCGGTTCGGACCGCCAAGCATCTGGCTCCACTGCTAGTG
  TCCTAAATTTGAATGGCAAACACAAATAAGATTTAGCAATTCGTGTAGAC
  GACCGGGGACTTGCATGATGGGAGCAGCTTTGTTAAACTACGAACGTAAT
).join.chars

puts "SEQUENCE:"
i = 0
sequence.each_slice(50) do |row|
  puts "%5d: %s" % { i, row.join }
  i += 50
end
puts
puts "  BASECOUNT:"
sequence.tally.to_a.sort.each do |base, count|
  puts "      #{base}: #{count}"
end
puts "    TOT= #{sequence.size}"
