proc Main()
 byte CHARS, cursorinh=$2F0

 graphics(0) cursorinh=1

 position(2,2) printe("Action!")

 CHARS=Locate(2,2) position(2,2) put(CHARS)

 cursorinh=0
 position(2,4) printf("Character at column 2 row 2 was %C",CHARS)

return
