rows = 3
cols = 50
$end = 74
$zbl = Array.new($end+1,false)
$board = [[Cell[] ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]        ,Cell[]],
          [Cell[] ,Cell[1,1,1] ,Cell[1,2,0] ,Cell[1,3,0] ,Cell[]      ,Cell[]      ,Cell[1,6,0] ,Cell[1,7,0] ,Cell[]      ,Cell[]      ,Cell[1,10,0] ,Cell[1,11,0] ,Cell[]       ,Cell[]       ,Cell[1,14,0] ,Cell[1,15,0] ,Cell[]       ,Cell[]       ,Cell[1,18,0] ,Cell[1,19,0] ,Cell[]       ,Cell[]       ,Cell[1,22,0] ,Cell[1,23,0] ,Cell[]       ,Cell[]       ,Cell[1,26,0] ,Cell[1,27,0] ,Cell[]       ,Cell[]       ,Cell[1,30,0] ,Cell[1,31,0] ,Cell[]       ,Cell[]       ,Cell[1,34,0] ,Cell[1,35,0] ,Cell[]       ,Cell[]       ,Cell[1,38,0] ,Cell[1,39,0] ,Cell[]       ,Cell[]       ,Cell[1,42,0] ,Cell[1,43,0] ,Cell[]       ,Cell[]       ,Cell[1,46,0] ,Cell[1,47,0] ,Cell[]       ,Cell[]       ,Cell[1,50,74] ,Cell[]],
          [Cell[] ,Cell[]      ,Cell[]      ,Cell[2,3,0] ,Cell[]      ,Cell[2,5,0] ,Cell[]      ,Cell[2,7,0] ,Cell[]      ,Cell[2,9,0] ,Cell[]       ,Cell[2,11,0] ,Cell[]       ,Cell[2,13,0] ,Cell[]       ,Cell[2,15,0] ,Cell[]       ,Cell[2,17,0] ,Cell[]       ,Cell[2,19,0] ,Cell[]       ,Cell[2,21,0] ,Cell[]       ,Cell[2,23,0] ,Cell[]       ,Cell[2,25,0] ,Cell[]       ,Cell[2,27,0] ,Cell[]       ,Cell[2,29,0] ,Cell[]       ,Cell[2,31,0] ,Cell[]       ,Cell[2,33,0] ,Cell[]       ,Cell[2,35,0] ,Cell[]       ,Cell[2,37,0] ,Cell[]       ,Cell[2,39,0] ,Cell[]       ,Cell[2,41,0] ,Cell[]       ,Cell[2,43,0] ,Cell[]       ,Cell[2,45,0] ,Cell[]       ,Cell[2,47,0] ,Cell[]       ,Cell[2,49,0] ,Cell[]        ,Cell[]],
          [Cell[] ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[3,4,0] ,Cell[3,5,0] ,Cell[]      ,Cell[]      ,Cell[3,8,0] ,Cell[3,9,0] ,Cell[]       ,Cell[]       ,Cell[3,12,0] ,Cell[3,13,0] ,Cell[]       ,Cell[]       ,Cell[3,16,0] ,Cell[3,17,0] ,Cell[]       ,Cell[]       ,Cell[3,20,0] ,Cell[3,21,0] ,Cell[]       ,Cell[]       ,Cell[3,24,0] ,Cell[3,25,0] ,Cell[]       ,Cell[]       ,Cell[3,28,0] ,Cell[3,29,0] ,Cell[]       ,Cell[]       ,Cell[3,32,0] ,Cell[3,33,0] ,Cell[]       ,Cell[]       ,Cell[3,36,0] ,Cell[3,37,0] ,Cell[]       ,Cell[]       ,Cell[3,40,0] ,Cell[3,41,0] ,Cell[]       ,Cell[]       ,Cell[3,44,0] ,Cell[3,45,0] ,Cell[]       ,Cell[]       ,Cell[3,48,0] ,Cell[3,49,0] ,Cell[]        ,Cell[]],
          [Cell[] ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]      ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]       ,Cell[]        ,Cell[]]]

test(rows, cols, 1, 1)
