INT FUNC Gcd(INT a,b)
  INT tmp

  IF a<b THEN
    tmp=a a=b b=tmp
  FI

  WHILE b#0
  DO
    tmp=a MOD b
    a=b b=tmp
  OD
RETURN (a)

BYTE FUNC Contains(INT v INT ARRAY a INT count)
  INT i

  FOR i=0 TO count-1
  DO
    IF a(i)=v THEN
      RETURN (1)
    FI
  OD
RETURN (0)

BYTE FUNC Skip(INT v INT ARRAY a INT count)
  IF Contains(v,a,count) THEN
    RETURN (1)
  ELSEIF Gcd(v,a(count-1))>1 THEN
    RETURN (1)
  ELSEIF Gcd(v,a(count-2))>1 THEN
    RETURN (1)
  FI
RETURN (0)

BYTE FUNC CoprimeTriplets(INT limit INT ARRAY a)
  INT i,count

  a(0)=1 a(1)=2
  count=2

  DO
    i=3
    WHILE Skip(i,a,count)
    DO
      i==+1
    OD
    IF i>=limit THEN
      RETURN (count)
    FI
    a(count)=i
    count==+1
  OD
RETURN (count)

PROC Main()
  DEFINE LIMIT="50"
  INT ARRAY a(LIMIT)
  INT i,count

  count=CoprimeTriplets(LIMIT,a)
  FOR i=0 TO count-1
  DO
    PrintI(a(i)) Put(32)
  OD
  PrintF("%E%EThere are %I coprimes less than %I",count,LIMIT)
RETURN
