PROC Wait(BYTE frames)
  BYTE RTCLOK=$14
  frames==+RTCLOK
  WHILE frames#RTCLOK DO OD
RETURN

PROC Main()
  INT size=[960]
  BYTE ARRAY buffer(size)
  BYTE POINTER ptr

  Graphics(0)
  Position(2,10)
  Print("This is the original screen content.")
  Wait(200)

  ptr=PeekC(88)
  MoveBlock(buffer,ptr,size) ;copy screen content

  Put(125) ;clear screen
  Wait(50)
  Position(1,10)
  Print("This is an alternative screen content.")

  Wait(200)
  MoveBlock(ptr,buffer,size) ;restore screen content
RETURN
