INCLUDE "D2:SORT.ACT" ;from the Action! Tool Kit

DEFINE PTR="CARD"

PROC PrintArray(BYTE ARRAY a BYTE len)
  BYTE i

  Print("  [")
  IF len>0 THEN
    FOR i=0 TO len-1
    DO
      PrintB(a(i))
      IF i<len-1 THEN Put(' ) FI
    OD
  FI
  PrintE("]")
RETURN

BYTE FUNC Contains(BYTE ARRAY a BYTE len,value)
  BYTE i

  IF len>0 THEN
    FOR i=0 TO len-1
    DO
      IF a(i)=value THEN RETURN(1) FI
    OD
  FI
RETURN (0)

PROC CommonListElements(PTR ARRAY arrays
  BYTE ARRAY lengths BYTE count
  BYTE ARRAY res BYTE POINTER resLen)

  BYTE ARRAY a
  BYTE i,j,len,value,cnt,maxcnt

  resLen^=0
  IF count=0 THEN
    RETURN
  ELSEIF count=1 THEN
    MoveBlock(res,a,len) RETURN
  FI

  FOR i=0 TO count-1
  DO
    a=arrays(i) len=lengths(i)
    IF len>0 THEN
      FOR j=0 TO len-1
      DO
        value=a(j)
        IF Contains(res,resLen^,value)=0 THEN
          res(resLen^)=value resLen^==+1
        FI
      OD
    FI
  OD
  SortB(res,resLen^,0)
RETURN

PROC Test(PTR ARRAY arrays BYTE ARRAY lengths BYTE count)
  BYTE ARRAY res(100)
  BYTE len,i

  CommonListElements(arrays,lengths,count,res,@len)
  PrintE("Input:")
  FOR i=0 TO count-1
  DO
    PrintArray(arrays(i),lengths(i))
  OD
  PrintE("Output:")
  PrintArray(res,len) PutE()
RETURN

PROC Main()
  PTR ARRAY arrays(3)
  BYTE ARRAY
    lengths(3)=[8 5 4],
    a1(8)=[5 1 3 8 9 4 8 7],
    a2(5)=[3 5 9 8 4],
    a3(4)=[1 3 7 9],
    a4(8)=[5 1 1 1 9 9 8 7],
    a5(5)=[5 5 9 9 9],
    a6(4)=[1 7 7 9]
  BYTE len

  Put(125) PutE() ;clear the screen

  arrays(0)=a1 arrays(1)=a2 arrays(2)=a3
  Test(arrays,lengths,3)

  arrays(0)=a4 arrays(1)=a5 arrays(2)=a6
  Test(arrays,lengths,3)

  lengths(0)=0
  Test(arrays,lengths,3)
RETURN
