(defun y-or-n ()
  (clear-input *standard-input*)
  (loop as dum = (format t "Y or N for yes or no: ")
        as c = (read-char)
        as q = (and (not (equal c #\n)) (not (equal c #\y)))
        when q do (format t "~%Need Y or N~%")
        unless q return (if (equal c #\y) 'yes 'no)))
