CL-USER> (loop for previous-value = nil then value
               for value = #*01110110101010100100 then (next-cycle value)
               until (equalp value previous-value)
               do (print-world value))
.###.##.#.#.#.#..#..
.#.#####.#.#.#......
..##...##.#.#.......
..##...###.#........
..##...#.##.........
..##....###.........
..##....#.#.........
..##.....#..........
..##................
