PROC Main()
  BYTE count=[10],row,item
  CHAR ARRAY s(5)
  INT v

  FOR row=0 TO count-1
  DO
    v=1
    FOR item=0 TO row
    DO
      StrI(v,s)
      Position(2*(count-row)+4*item-s(0),row+1)
      Print(s)
      v=v*(row-item)/(item+1)
    OD
    PutE()
  OD
RETURN
