TYPE Object=[
  BYTE byteData
  INT intData
  CARD cardData]

PROC IsNull(Object POINTER ptr)
  IF ptr=0 THEN
    PrintE("Object is null")
  ELSE
    PrintE("Object is not null")
  FI
RETURN

PROC Main()
  Object a
  Object POINTER ptr1=a,ptr2=0

  IsNull(ptr1)
  IsNull(ptr2)
RETURN
