INCLUDE "D2:PRINTF.ACT" ;from the Action! Tool Kit

PROC Main()
  CARD ARRAY v=[6502 1977 2021 256 1024 12345 9876 1111 0 16]
  BYTE i,LMARGIN=$52,old

  old=LMARGIN
  LMARGIN=0 ;remove left margin on the screen
  Put(125) PutE() ;clear the screen

  FOR i=0 TO 9
  DO
    PrintF("(dec) %D = (hex) %H = (oct) %O%E",v(i),v(i),v(i))
  OD

  LMARGIN=old ;restore left margin on the screen
RETURN
