class Camera (instanceVars)
    # methods...
    # initializer...
end

class Phone (instanceVars)
    # methods...
    # initializer...
end

class CameraPhone : Camera, Phone (instanceVars)
    # methods...
    # initialiser...
end
