PROC Main()
  DEFINE PTR="CARD"
  BYTE i
  PTR ARRAY items(10)
  items(0)="First"   items(1)="Second"
  items(2)="Third"   items(3)="Fourth"
  items(4)="Fifth"   items(5)="Sixth"
  items(6)="Seventh" items(7)="Eighth"
  items(8)="Ninth"   items(9)="Tenth"

  PrintE("In Action! there is no for-each loop")
  PutE()
  FOR i=0 TO 9
  DO
    PrintE(items(i))
  OD
RETURN
