x$ = "123, 12345, 1234567, 987654321, 10001, -10001, -123, -100, 100, -12345, 1, 2, -1, -10, 2002, -2002, 0"

while word$(x$,i+1,",") <> ""
 i	= i + 1
 a1$	= trim$(word$(x$,i,","))
 if left$(a1$,1) = "-" then a$ = mid$(a1$,2) else a$ = a1$
 if (len(a$) and 1) = 0 or len(a$) < 3 then
   print a1$;chr$(9);" length < 3 or is even"
  else
   print mid$(a$,((len(a$)-3)/2)+1,3);" ";a1$
 end if
wend
end
