PROC Main()
  DEFINE LEN="8"
  BYTE ARRAY coins=[200 100 50 20 10 5 2 1],count(LEN)
  BYTE i
  INT value=[988],curr,total

  Zero(count,LEN)
  i=0 total=0
  curr=value
  WHILE curr>0
  DO
    IF curr>=coins(i) THEN
      count(i)==+1
      total==+1
      curr==-coins(i)
    ELSE
      i==+1
    FI
  OD

  PrintF("%I coins to make %I:%E",total,value)
  FOR i=0 TO LEN-1
  DO
    IF count(i) THEN
      PrintF("  %B x %B%E",count(i),coins(i))
    FI
  OD
RETURN
