PROC CountVovelsConsonants(CHAR ARRAY s BYTE POINTER vov,con)
  BYTE i
  CHAR c

  vov^=0 con^=0
  FOR i=1 TO s(0)
  DO
    c=s(i)
    IF c>='A AND c<='Z THEN
      c==+'a-'A
    FI
    IF c>='a AND c<='z THEN
      IF c='a OR c='e OR c='i OR c='o OR c='u THEN
        vov^==+1
      ELSE
        con^==+1
      FI
    FI
  OD
RETURN

PROC Test(CHAR ARRAY s)
  BYTE vov,con

  PrintE("Input string:")
  PrintE(s)
  CountVovelsConsonants(s,@vov,@con)
  PrintF("Vovel count=%I, consonant count=%I%E%E",vov,con)
RETURN

PROC Main()
  Test("Now is the time for all good men to come to the aid of their country.")
  Test("Forever Action! programming language")
RETURN
