PROC ReadStream(BYTE stream)
  CHAR ARRAY line(255)

  WHILE Eof(stream)=0
  DO
    InputSD(stream,line)
    PrintE(line)
  OD
RETURN

PROC Main()
  BYTE streamId=[1]

  Close(streamId)
  Open(streamId,"H6:INPUT_PU.ACT",4)
  PrintE("Reading from stream...") PutE()
  ReadStream(streamId)
  Close(streamId)
RETURN
