card$(1) = "49927398716"
card$(2) = "49927398717"
card$(3) = "1234567812345678"
card$(4) = "1234567812345670"

for i = 1 to 4
print card$(i);" ";luhn$(card$(i))
next i

FUNCTION luhn$(card$)
    lc      = len(card$)
    for i   = lc to 1 step -1
      digit = val(mid$(card$,i,1))
      if ((lc -i) mod 2) = 0 then chkSum = chkSum + digit else chkSum = chkSum + int(digit * 2.2)
    next i
    if chkSum mod 10 = 0 then luhn$ = "True" else luhn$ = "False"
end function
