PROC PrintArray(INT ARRAY a INT len)
  INT i

  Put('[)
  FOR i=0 TO len-1
  DO
    PrintI(a(i))
    IF i<len-1 THEN
      Put(' )
    FI
  OD
  Put(']) PutE()
RETURN

PROC PrintPairs(INT ARRAY a INT len,sum)
  INT i,j,p1,p2,s,count

  count=0
  FOR i=0 TO len-2
  DO
    p1=a(i)
    FOR j=i+1 TO len-1
    DO
      p2=a(j)
      s=p1+p2
      IF s=sum THEN
        PrintF("(%I,%I) ",i,j)
        count==+1
      ELSEIF s>sum THEN
        EXIT
      FI
    OD
  OD
  IF count=0 THEN
    Print("none")
  FI
  PutE()
RETURN

PROC Test(INT ARRAY a INT len,sum)
  Print("Array: ") PrintArray(a,len)
  Print("Sum:   ") PrintIE(sum)
  Print("Pairs: ") PrintPairs(a,len,sum)
  PutE()
RETURN

PROC Main()
  INT ARRAY a=[0 2 11 19 90]
  INT ARRAY b=[0 2 3 3 4 11 17 17 18 19 90]

  Test(a,5,21)
  Test(a,5,22)
  Test(b,11,21)
RETURN
