EXAMPLES:
GUI, FONT,S8, COURIER
GUI, ADD, EDIT, VYR W40 R1 LIMIT4 NUMBER, 1969
GUI, ADD, EDIT, VEDIT2 W580 R38
GUI, ADD, BUTTON, DEFAULT HIDDEN GSUBMIT
GUI, SHOW

SUBMIT:
GUI, SUBMIT, NOHIDE
GUICONTROL,, EDIT2, % CALENDAR(YR)
RETURN

GUIESCAPE:
GUICLOSE:
EXITAPP
RETURN
