HAI 1.3

HOW IZ I MAKELIST YR SEP
    I HAS A COUNTER ITZ 1
    HOW IZ I MAKEITEM YR ITEM
        VISIBLE COUNTER SEP ITEM
        COUNTER R SUM OF COUNTER AN 1
    IF U SAY SO
    I IZ MAKEITEM YR "first" MKAY
    I IZ MAKEITEM YR "second" MKAY
    I IZ MAKEITEM YR "third" MKAY
IF U SAY SO

I IZ MAKELIST YR ". " MKAY

KTHXBYE
