PROC Main()
  CHAR ARRAY str1,str2,str3(10)

  str1="Atari"
  str2=str1
  SCopy(str3,str1)

  PrintF(" base=%S%E",str1)
  PrintF("alias=%S%E",str2)
  PrintF(" copy=%S%E",str3)
  PutE()

  SCopy(str1,"Action!")

  PrintF(" base=%S%E",str1)
  PrintF("alias=%S%E",str2)
  PrintF(" copy=%S%E",str3)
RETURN
