INCLUDE "H6:SIEVE.ACT"

INT FUNC GetNextPrime(INT i BYTE ARRAY primes)
  DO
    i==+1
  UNTIL primes(i)
  OD
RETURN (i)

PROC Main()
  DEFINE MAXPRIME="99"
  DEFINE MAX="200"
  BYTE ARRAY primes(MAX+1)
  INT i,p

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAX+1)
  FOR i=2 TO MAXPRIME
  DO
    IF primes(i) THEN
      p=GetNextPrime(i,primes)
      IF p<=MAXPRIME AND primes(i+p-1)=1 THEN
        PrintF("%I+%I-1=%I%E",i,p,i+p-1)
      FI
    FI
  OD
RETURN
