CARD FUNC GetNumber(BYTE x)
  CARD i,sq

  i=1
  DO
    sq=i*i
    WHILE sq>x
    DO
      sq==/10
    OD
    IF sq=x THEN
      RETURN (i*i)
    FI
    i==+1
  OD
RETURN (0)

PROC Main()
  BYTE i
  CARD num

  FOR i=1 TO 49
  DO
    num=GetNumber(i)
    PrintC(num) Put(32)
  OD
RETURN
