HAI 1.3

HOW IZ I REPEAT YR DEMANZ AN YR TIMEZ
  IM IN YR LOOP UPPIN YR VAR TIL BOTH SAEM VAR AN TIMEZ
    I IZ DEMANZ MKAY
  IM OUTTA YR LOOP
IF U SAY SO

HOW IZ I SAYHELLO
  VISIBLE "HELLO"
IF U SAY SO

I IZ REPEAT YR SAYHELLO AN YR 3 MKAY

KTHXBYE
