INCLUDE "D2:REAL.ACT" ;from the Action! Tool Kit

DEFINE REALPTR="CARD"
TYPE PointI=[INT x,y]
TYPE PointR=[REALPTR rx,ry]

PROC Main()
  PointI p1
  PointR p2
  REAL realx,realy

  Put(125) PutE() ;clear screen

  p1.x=123
  p1.y=4567

  ValR("12.34",realx)
  ValR("5.6789",realy)
  p2.rx=realx
  p2.ry=realy

  PrintF("Integer point p1=(%I,%I)%E",p1.x,p1.y)

  Print("Real point p2=(")
  PrintR(p2.rx) Print(",")
  PrintR(p2.ry) Print(")")
RETURN
