;;; Find some Riordan numbers - limited to the first 13 as the largest integer
;;;                             Action! supports is unsigned 16-bit

;;; sets a to the riordan numbers 0 .. n, a must have n elements
PROC riordan( CARD n CARD ARRAY a )
  CARD i

  IF n >= 0 THEN
    a( 0 ) = 1
    IF n >= 1 THEN
      a( 1 ) = 0
      FOR i = 2 TO n DO
        a( i ) = ( ( i - 1 )
                 * ( ( 2 * a( i - 1 ) )
                   + ( 3 * a( i - 2 ) )
                   )
                 )
               / ( i + 1 )
      OD
    FI
  FI
RETURN

PROC Main()
  CARD  ARRAY r( 13 )
  CARD i

  riordan( 13, r )
  FOR i = 0 TO 12 DO
    Put( '  )
    PrintC( r( i ) )
  OD
RETURN
