PROC Main()
  BYTE
    count=[96],rows=[16],
    first=[32],last=[127],
    i,j

  Put(125) ;clear screen

  FOR i=0 TO rows-1
  DO
    Position(2,3+i)

    FOR j=first+i TO last STEP rows
    DO
      IF j>=96 AND j<=99 THEN
        Put(' )
      FI
      PrintB(j)
      Put(' )

      IF j=32 THEN
        Print("SP ")
      ELSEIF j=125 THEN
        Print("CL")
      ELSEIF j=126 THEN
        Print("DL")
      ELSEIF j=127 THEN
        Print("TB")
      ELSE
        PrintF("%C  ",j)
      FI
    OD
    PutE()
  OD
RETURN
