BYTE FUNC FindC(CHAR ARRAY text CHAR c)
  BYTE i

  i=1
  WHILE i<=text(0)
  DO
    IF text(i)=c THEN
      RETURN (i)
    FI
    i==+1
  OD
RETURN (0)

BYTE FUNC IsAbcWord(CHAR ARRAY word)
  BYTE a,b,c

  a=FindC(word,'a)
  IF a=0 THEN RETURN (0) FI
  b=FindC(word,'b)
  IF b<a THEN RETURN (0) FI
  c=FindC(word,'c)
  IF c<b THEN RETURN (0) FI
RETURN (1)

PROC FindAbcWords(CHAR ARRAY fname)
  CHAR ARRAY line(256)
  CHAR ARRAY tmp(256)
  BYTE pos,dev=[1]

  pos=2
  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    IF IsAbcWord(line) THEN
      IF pos+line(0)>=40 THEN
        PutE() pos=2
      FI
      Print(line) Put(32)
      pos==+line(0)+1
    FI
  OD
  Close(dev)
RETURN

PROC Main()
  CHAR ARRAY fname="H6:UNIXDICT.TXT"

  FindAbcWords(fname)
RETURN
