empty_list = []
list = [1,2,3,4,5]
length(list)                    #=> 5
[0 | list]                      #=> [0,1,2,3,4,5]
hd(list)                        #=> 1
tl(list)                        #=> [2,3,4,5]
Enum.at(list,3)                 #=> 4
list ++ [6,7]                   #=> [1,2,3,4,5,6,7]
list -- [4,2]                   #=> [1,3,5]
