INCLUDE "D2:REAL.ACT" ;from the Action! Tool Kit

PROC Main()
  REAL sum,r
  INT i

  Put(125) PutE() ;clear the screen
  IntToReal(0,sum)
  FOR i=0 TO 999
  DO
    IF i MOD 3=0 OR i MOD 5=0 THEN
      IntToReal(i,r)
      RealAdd(sum,r,sum)
    FI
  OD

  PrintRE(sum)
RETURN
