PROC PrintNum(BYTE x)
  Put(32)
  IF x<10 THEN Put(32) FI
  IF x<100 THEN Put(32) FI
  PrintB(x)
RETURN

PROC Main()
  DEFINE MAX="100"
  BYTE ARRAY div(MAX+1)
  BYTE i,j,LMARGIN=$52,oldLMARGIN

  oldLMARGIN=LMARGIN
  LMARGIN=0 ;remove left margin on the screen
  Put(125) PutE() ;clear the screen

  SetBlock(div,MAX+1,1)
  FOR i=2 TO MAX
  DO
    FOR j=i TO MAX STEP i
    DO
      div(j)==+i
    OD
  OD

  FOR i=1 TO MAX
  DO
    PrintNum(div(i))
  OD

  LMARGIN=oldLMARGIN ;restore left margin on the screen
RETURN
