val data=List(List("a","b","c"), List("","q","z"), List("zap","zip","Zot"))
println(data)
   //-> List(List(a, b, c), List(, q, z), List(zap, zip, Zot))
println(sortTable(data))
   //-> List(List(, q, z), List(a, b, c), List(zap, zip, Zot))
println(sortTable(data, reverse=true))
   //-> List(List(zap, zip, Zot), List(a, b, c), List(, q, z))
println(sortTable(data, column=2))
   //-> List(List(zap, zip, Zot), List(a, b, c), List(, q, z))
println(sortTable(data, ((a, b)=> b.size<a.size)))
   //-> List(List(zap, zip, Zot), List(a, b, c), List(, q, z))
