public class Animal{
   //functions go here...
}
public class Dog extends Animal{
   //functions go here...
}
public class Cat extends Animal{
   //functions go here...
}
public class Lab extends Dog{
   //functions go here...
}
public class Collie extends Dog{
   //functions go here...
}
