CARD FUNC DecodeRomanDigit(CHAR c)
  IF c='I THEN RETURN (1)
  ELSEIF c='V THEN RETURN (5)
  ELSEIF c='X THEN RETURN (10)
  ELSEIF c='L THEN RETURN (50)
  ELSEIF c='C THEN RETURN (100)
  ELSEIF c='D THEN RETURN (500)
  ELSEIF c='M THEN RETURN (1000)
  FI
RETURN (0)

CARD FUNC DecodeRomanNumber(CHAR ARRAY s)
  CARD res,curr,prev
  BYTE i

  res=0 prev=0 i=s(0)
  WHILE i>0
  DO
    curr=DecodeRomanDigit(s(i))
    IF curr<prev THEN
      res==-curr
    ELSE
      res==+curr
    FI
    prev=curr
    i==-1
  OD
RETURN (res)

PROC Test(CHAR ARRAY s)
  CARD n

  n=DecodeRomanNumber(s)
  PrintF("%S=%U%E",s,n)
RETURN

PROC Main()
  Test("MCMXC")
  Test("MMVIII")
  Test("MDCLXVI")
  Test("MMMDCCCLXXXVIII")
  Test("MMMCMXCIX")
RETURN
