BYTE Func IsStrangeNumber(INT i)
  BYTE ARRAY primes=[0 0 1 1 0 1 0 1 0 0]
  BYTE d,diff,prev

  prev=255
  WHILE i#0
  DO
    d=i MOD 10
    IF prev#255 THEN
      IF prev>d THEN
        diff=prev-d
      ELSE
        diff=d-prev
      FI
      IF primes(diff)=0
        THEN RETURN (0)
      FI
    FI
    prev=d
    i==/10
  OD
RETURN (1)

PROC Main()
  INT i,count=[0]

  FOR i=101 TO 499
  DO
    IF IsStrangeNumber(i) THEN
      PrintI(i) Put(32)
      count==+1
    FI
  OD
  PrintF("%E%EThere are %I strange numbers",count)
RETURN
