BYTE FUNC IsPrime(CARD a)
  CARD i

  IF a<=1 THEN
    RETURN (0)
  FI

  FOR i=2 TO a/2
  DO
    IF a MOD i=0 THEN
      RETURN (0)
    FI
  OD
RETURN (1)

PROC PrintPrimes(CARD begin,end)
  BYTE notFirst
  CARD i

  notFirst=0
  FOR i=begin TO end
  DO
    IF IsPrime(i) THEN
      IF notFirst THEN
        Print(", ")
      FI
      notFirst=1
      PrintC(i)
    FI
  OD
RETURN

PROC Main()
  CARD begin=[2000],end=[3000]

  PrintF("Primes in range [%U..%U]:%E",begin,end)
  PrintPrimes(begin,end)
RETURN
