BYTE FUNC Check(INT x)
  BYTE d
  INT tmp,prod

  prod=1 tmp=x
  WHILE tmp#0
  DO
    d=tmp MOD 10
    IF x MOD d#0 THEN
      RETURN (0)
    FI
    tmp==/10
    prod==*d
  OD
  IF x MOD prod=0 THEN
    RETURN (0)
  FI
RETURN (1)

PROC Main()
  INT i

  FOR i=1 TO 999
  DO
    IF Check(i) THEN
      PrintI(i) Put(32)
    FI
  OD
RETURN
