BYTE FUNC Once(CHAR ARRAY text CHAR c)
  BYTE i,n

  i=1 n=0
  FOR i=1 TO text(0)
  DO
    IF text(i)=c THEN
      n==+1
      IF n>1 THEN
        RETURN (0)
      FI
    FI
  OD
  IF n=1 THEN
    RETURN (1)
  FI
RETURN (0)

BYTE FUNC IsValidWord(CHAR ARRAY word)
  IF word(0)<=10 THEN RETURN (0) FI
  IF Once(word,'a)=0 THEN RETURN(0) FI
  IF Once(word,'e)=0 THEN RETURN(0) FI
  IF Once(word,'i)=0 THEN RETURN(0) FI
  IF Once(word,'o)=0 THEN RETURN(0) FI
  IF Once(word,'u)=0 THEN RETURN(0) FI
RETURN (1)

PROC FindWords(CHAR ARRAY fname)
  CHAR ARRAY line(256)
  CHAR ARRAY tmp(256)
  BYTE pos,dev=[1]

  pos=2
  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    IF IsValidWord(line) THEN
      IF pos+line(0)>=39 THEN
        PutE() pos=2
      FI
      Print(line) Put(32)
      pos==+line(0)+1
    FI
  OD
  Close(dev)
RETURN

PROC Main()
  CHAR ARRAY fname="H6:UNIXDICT.TXT"

  FindWords(fname)
RETURN
