PROC CalcDivisors(INT x INT ARRAY div INT POINTER count)
  INT i

  count^=0
  FOR i=1 TO x/2
  DO
    IF x MOD i=0 THEN
      div(count^)=i
      count^==+1
    FI
  OD
RETURN

INT FUNC Reverse(INT x)
  INT res

  res=0
  WHILE x#0
  DO
    res==*10
    res==+x MOD 10
    x==/10
  OD
RETURN (res)

BYTE FUNC IsSpecial(INT x)
  INT ARRAY divisors(100)
  INT count,i,rev,revd

  CalcDivisors(x,divisors,@count)
  rev=Reverse(x)
  FOR i=0 TO count-1
  DO
    revd=Reverse(divisors(i))
    IF rev MOD revd#0 THEN
      RETURN (0)
    FI
  OD
RETURN (1)

PROC Main()
  INT i

  FOR i=1 TO 199
  DO
    IF IsSpecial(i) THEN
      PrintI(i) Put(32)
    FI
  OD
RETURN
