PROC Main()
  BYTE n,min=[1],max=[100]
  CHAR c

  PrintF("Think a number in range %B-%B%E",min,max)
  DO
    n=(max+min) RSH 1
    PrintF("My guess is %B%E",n)
    PrintF("Is it (E)qual, (L)ower or (H)igher?")
    c=GetD(7)
    Put(c) PutE()
    IF c='E THEN
      Print("I guessed!")
      EXIT
    ELSEIF c='L THEN
      max=n-1
    ELSEIF c='H THEN
      min=n+1
    FI
    IF max<min THEN
      Print("You are cheating...")
      EXIT
    FI
  OD
RETURN
