PROC PrintFactors(CARD a)
  BYTE notFirst
  CARD p

  p=1 notFirst=0
  WHILE p<=a
  DO
    IF a MOD p=0 THEN
      IF notFirst THEN
        Print(", ")
      FI
      notFirst=1
      PrintC(p)
    FI
    p==+1
  OD
RETURN

PROC Test(CARD a)
  PrintF("Factors of %U: ",a)
  PrintFactors(a)
  PutE()
RETURN

PROC Main()
  Test(1)
  Test(101)
  Test(666)
  Test(1977)
  Test(2021)
  Test(6502)
  Test(12345)
RETURN
