INCLUDE "H6:REALMATH.ACT"

PROC ArcLength(REAL POINTER r,a1,a2,len)
  REAL tmp1,tmp2,r180,r360,pi

  IntToReal(360,r360)
  IntToReal(180,r180)
  ValR("3.14159265",pi)
  RealAbsDiff(a1,a2,tmp1)     ;tmp1=abs(a1-a2)
  RealSub(r360,tmp1,tmp2) ;tmp2=360-abs(a1-a2)
  RealMult(tmp2,pi,tmp1)  ;tmp1=(360-abs(a1-a2))*pi
  RealMult(tmp1,r,tmp2)   ;tmp2=(360-abs(a1-a2))*pi*r
  RealDiv(tmp2,r180,len)  ;len=(360-abs(a1-a2))*pi*r/180
RETURN

PROC Main()
  REAL r,a1,a2,len

  Put(125) PutE() ;clear screen
  Print("Length of arc: ")
  IntToReal(10,r)
  IntToReal(10,a1)
  IntToReal(120,a2)
  ArcLength(r,a1,a2,len)
  PrintR(len)
RETURN
