(define (egyptian-divide dividend divisor)
  (let* ((max-bits 32)
         (table (make-vector (+ max-bits 1)))
         (i 1))

    (vector-set! table i (cons 1 divisor))

    (let loop-build ()
      (let* ((pair   (vector-ref table i))
             (power  (car pair))
             (value  (cdr pair)))
        (when (< value dividend)
          (set! i (+ i 1))
          (vector-set! table i (cons (* 2 power) (* 2 value)))
          (loop-build))))

    (set! i (- i 1))
    (let* ((pair-i (vector-ref table i))
           (answer (car pair-i))
           (accumulator (cdr pair-i)))

      (let loop ()
        (when (> i 1)
          (set! i (- i 1))
          (let* ((p (vector-ref table i))
                 (pow (car p))
                 (val (cdr p)))
            (when (<= (+ val accumulator) dividend)
              (set! answer (+ answer pow))
              (set! accumulator (+ accumulator val))))
          (loop)))

      (let ((remainder (- dividend accumulator)))
        (list answer remainder)))))

(let* ((dividend 580)
       (divisor  34)
       (res      (egyptian-divide dividend divisor))
       (q        (car res))
       (r        (cadr res)))
  (display (number->string dividend))
  (display " divided by ")
  (display (number->string divisor))
  (display " using Egyptian division returns ")
  (display (number->string q))
  (display " mod(ulus) ")
  (display (number->string r))
  (newline))
