INCLUDE"REAL.ACT" ;from the Action! Tool Kit

proc MAIN()
 byte array astring
 byte IOCB1=$350,ICAX3=IOCB1+12,ICAX4=IOCB1+13,ICAX5=IOCB1+14
 real A,B,C,FLEN

 open(1,"D:REAL.ACT",4,0) xio(1,0,39,"D:REAL.ACT") close(1)

 IntToReal(ICAX3,FLEN)
 IntToReal(ICAX4,A) astring="256"   ValR(astring,B) RealMult(A,B,C) RealAdd(FLEN,C,FLEN)
 IntToReal(ICAX5,A) astring="65536" ValR(astring,B) RealMult(A,B,C) RealAdd(FLEN,C,FLEN)
 print("Size of REAL.ACT is ") printRD(DEVICE,FLEN) printe(" bytes")
return
