PROC CheckIsEmpty(CHAR ARRAY s)
  PrintF("'%S' is empty? ",s)
  IF s(0)=0 THEN
    PrintE("True")
  ELSE
    PrintE("False")
  FI
RETURN

PROC Main()
  CHAR ARRAY str1,str2

  str1=""
  str2="text"

  CheckIsEmpty(str1)
  CheckIsEmpty(str2)
RETURN
