HAI 1.3

HOW IZ I ADDSUB YR X AN YR Y
  I HAS A REZULT ITZ A BUKKIT
  REZULT HAS A SRS 0 ITZ SUM OF X AN Y
  REZULT HAS A SRS 1 ITZ DIFF OF X AN Y
  FOUND YR REZULT
IF U SAY SO

I HAS A THING ITZ I IZ ADDSUB YR 15 AN YR 3 MKAY
VISIBLE THING'Z SRS 0 ", " THING'Z SRS 1

KTHXBYE
