CL-USER> (sb-debug:backtrace 7)
0: (SB-DEBUG::MAP-BACKTRACE
    #<CLOSURE (LAMBDA (SB-DEBUG::FRAME)) {1193EFCD}>)[:EXTERNAL]
1: (BACKTRACE
    7
    #<TWO-WAY-STREAM
      :INPUT-STREAM #<SWANK-BACKEND::SLIME-INPUT-STREAM {120F6519}>
      :OUTPUT-STREAM #<SWANK-BACKEND::SLIME-OUTPUT-STREAM {1208F3E1}>>)
2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (BACKTRACE 7) #<NULL-LEXENV>)
3: (SWANK::EVAL-REGION
    "(sb-debug:backtrace 7)
")
4: ((LAMBDA ()))
5: (SWANK::TRACK-PACKAGE #<CLOSURE (LAMBDA ()) {1193ECBD}>)
6: (SWANK::CALL-WITH-RETRY-RESTART
    "Retry SLIME REPL evaluation request."
    #<CLOSURE (LAMBDA ()) {1193EC4D}>)
