HAI 1.3

HOW IZ I BASELSUM YR N
    I HAS A RESULT ITZ 0.0
    IM IN YR LOOP UPPIN YR K TIL BOTH SAEM K AN N
        I HAS A KK ITZ SUM OF K AN 1.0
        RESULT R SUM OF RESULT AN QUOSHUNT OF 1.0 AN PRODUKT OF KK AN KK
    IM OUTTA YR LOOP
    FOUND YR RESULT
IF U SAY SO

VISIBLE I IZ BASELSUM YR 1000 MKAY

KTHXBYE
