INT FUNC SumOfDigits(INT a)
  INT sum

  sum=0
  WHILE a#0
  DO
    sum==+a MOD 10
    a==/10
  OD
RETURN (sum)

INT FUNC Next(INT a)
  INT sum

  DO
    a==+1
    sum=SumOfDigits(a)
  UNTIL a MOD sum=0
  OD
RETURN (a)

PROC Main()
  INT i,a

  a=0
  FOR i=1 TO 20
  DO
    a=Next(a)
    PrintI(a)
    Put(32)
  OD
  Print("... ")
  a=Next(1000)
  PrintIE(a)
RETURN
