Collapse ← (1»≠⟜«)⊸/

>⍉ ⊢‿Collapse (≠⋈"<<<"⊸∾∘∾⟜">>>")∘{𝕎𝕩}⌜ ⟨
  "The better the 4-wheel drive, the further you'll be from help when ya get stuck!"
  "headmistressship"
  ""
  """If I were two-faced, would I be wearing this one?"" --- Abraham Lincoln "
  "..1111111111111111111111111111111111111111111111111111111111111117777888"
  "I never give 'em hell, I just tell the truth, and they think it's hell. "
  "                                                    --- Harry S Truman  "
⟩
