PROC Encode(INT x CHAR ARRAY s)
  INT ARRAY fib(22)=
    [1 2 3 5 8 13 21 34 55 89 144 233 377 610
    987 1597 2584 4181 6765 10946 17711 28657]
  INT i
  BYTE append

  IF x=0 THEN
    s(0)=1
    s(1)='0
    RETURN
  FI

  i=21 append=0
  s(0)=0
  WHILE i>=0
  DO
    IF x>=fib(i) THEN
      x==-fib(i)
      s(0)==+1
      s(s(0))='1
      append=1
    ELSEIF append THEN
      s(0)==+1
      s(s(0))='0
    FI
    i==-1
  OD
RETURN

PROC Main()
  INT i
  CHAR ARRAY s(10)

  FOR i=0 TO 20
  DO
    Encode(i,s)
    PrintF("%I -> %S%E",i,s)
  OD
RETURN
