HAI 1.3

HOW IZ I STRREP YR S AN YR N
    I HAS A OUTPUT ITZ ""
    IM IN YR LOOP UPPIN YR M TIL BOTH SAEM N AN M
        OUTPUT R SMOOSH OUTPUT S MKAY
    IM OUTTA YR LOOP
    FOUND YR OUTPUT
IF U SAY SO

VISIBLE I IZ STRREP YR "HA" AN YR 5 MKAY

KTHXBYE
