(defun guess-the-number ()
  (let ((num-guesses 0)
	(num (1+ (random 9)))
	(guess nil))
    (format t "Try to guess a number from 1 to 10!~%")
    (loop do (format t "Guess? ")
	  (incf num-guesses)
	  (setf guess (read))
	  (cond ((not (numberp guess))
		 (format t "Your guess is  not a number!~%"))
		((not (= guess num))
		 (format t "Your guess was wrong.  Try again.~%")))
	  until (and (numberp guess)
		     (= guess num)))
    (format t "You guessed correctly on the ~:r try!~%" num-guesses)))
