HAI 1.4

CAN HAS STRING?

HOW IZ I SPLITBYCHAR YR S
    I HAS A L ITZ STRING IZ LEN YR S MKAY
    I HAS A PREV
    IM IN YR LOOP UPPIN YR N TIL BOTH SAEM N AN L
        I HAS A CURR ITZ STRING IZ AT YR S AN YR N MKAY
        EITHER OF BOTH SAEM N AN 0 AN BOTH SAEM CURR AN PREV, O RLY?
            YA RLY, VISIBLE CURR!
            NO WAI, VISIBLE ", " CURR!
        OIC
        PREV R CURR
    IM OUTTA YR LOOP
    VISIBLE ""
IF U SAY SO

I IZ SPLITBYCHAR YR "gHHH5YY++///\ ,," MKAY

KTHXBYE
