       TYPE RS232PIN9
        LOGICAL CARRIER_DETECT		!1
        LOGICAL RECEIVED_DATA		!2
        LOGICAL TRANSMITTED_DATA	!3
        LOGICAL DATA_TERMINAL_READY	!4
        LOGICAL SIGNAL_GROUND		!5
        LOGICAL DATA_SET_READY		!6
        LOGICAL REQUEST_TO_SEND		!7
        LOGICAL CLEAR_TO_SEND		!8
        LOGICAL RING_INDICATOR		!9
       END TYPE RS232PIN9
