PROC ReadFastaFile(CHAR ARRAY fname)
  CHAR ARRAY line(256)
  CHAR ARRAY tmp(256)
  BYTE newLine,dev=[1]

  newLine=0
  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    IF line(0)>0 AND line(1)='> THEN
      IF newLine THEN
        PutE()
      FI
      newLine=1
      SCopyS(tmp,line,2,line(0))
      Print(tmp) Print(": ")
    ELSE
      Print(line)
    FI
  OD
  Close(dev)
RETURN

PROC Main()
  CHAR ARRAY fname="H6:FASTA.TXT"

  ReadFastaFile(fname)
RETURN
