DEFINE NO_KEY="255"
DEFINE KEY_Y="43"
DEFINE KEY_N="35"

PROC Main()
  BYTE CH=$02FC ;Internal hardware value for last key pressed
  BYTE k
  INT a,b

  DO
    Print("Input integer value a=")
    a=InputI()
    Print("Input integer value b=")
    b=InputI()

    PrintF("a+b=%I%E",a+b)
    PrintF("a-b=%I%E",a-b)
    PrintF("a*b=%I%E",a*b)
    PrintF("a/b=%I%E",a/b)
    PrintF("a MOD b=%I%E",a MOD b)

    PutE()
    PrintE("Again? (Y/N)")

    CH=NO_KEY ;Flush the keyboard
    DO
      k=CH
    UNTIL k=KEY_Y OR k=KEY_N
    OD
    CH=NO_KEY ;Flush the keyboard

    IF k=KEY_N THEN
      EXIT
    FI
  OD
RETURN
