PROC Main()
  BYTE x,y,z,n
  BYTE ARRAY nuggets(101)

  FOR n=0 TO 100
  DO
    nuggets(n)=0
  OD

  FOR x=0 TO 100 STEP 6
  DO
    FOR y=0 TO 100 STEP 9
    DO
      FOR z=0 TO 100 STEP 20
      DO
        n=x+y+z
        IF n<=100 THEN
          nuggets(n)=1
        FI
      OD
    OD
  OD

  n=100
  DO
    IF nuggets(n)=0 THEN
      PrintF("The largest non McNugget number is %B%E",n)
      EXIT
    ELSEIF n=0 THEN
      PrintE("There is no result")
      EXIT
    ELSE
      n==-1
    FI
  OD
RETURN
