;;; Find some De Polignac numbers: positive odd numbers that can't be
;;;      written as p + 2**n for some prime p and integer n

INCLUDE "H6:SIEVE.ACT"

PROC showDePolignac( CARD dpNumber )
  Put(' )
  IF dpNumber <   10 THEN Put(' ) FI
  IF dpNumber <  100 THEN Put(' ) FI
  IF dpNumber < 1000 THEN Put(' ) FI
  PrintC( dpNumber )
RETURN

PROC Main()
  DEFINE MAX_DP = "4000", MAX_POWER_OF_2 = "11"

  BYTE ARRAY primes(MAX_DP+1)
  CARD ARRAY powersOf2(MAX_POWER_OF_2+1) =
                 [1 2 4 8 16 32 64 128 256 512 1024 2048]
  CARD i, p, count
  BYTE found

  Sieve(primes,MAX_DP+1)

  ; the numbers must be odd and not of the form p + 2**n
  ; either p is odd and 2**n is even and hence n > 0 and p > 2
  ;     or 2**n is odd and p is even and hence n = 0 and p = 2

  ; n = 0, p = 2 - the only possibility is 3
  FOR i = 1 TO 3 STEP 2 DO
    p = 2
    IF p + 1 <> i THEN
      count ==+ 1
      showDePolignac( i )
    FI
  OD
  ; n > 0, p > 2
  i = 3
  WHILE i < MAX_DP AND count < 50 DO
    i ==+ 2
    found = 0
    p = 1
    WHILE found = 0 AND p <= MAX_POWER_OF_2 AND i > powersOf2( p ) DO
       found = primes( i - powersOf2( p ) )
       p ==+ 1
    OD
    IF found = 0 THEN
      count ==+ 1
      showDePolignac( i )
      IF count MOD 10 = 0 THEN PutE() FI
    FI
  OD

RETURN
