PROC Main()
  BYTE x,n,min=[1],max=[10]

  PrintF("Try to guess a number %B-%B: ",min,max)
  x=Rand(max-min+1)+min
  DO
    n=InputB()
    IF n=x THEN
      PrintE("Well guessed!")
      EXIT
    ELSE
      Print("Incorrect. Try again: ")
    FI
  OD
RETURN
