PROC PrintTable(INT ARRAY tab INT size)
  INT i

  Put('[)
  FOR i=0 TO size-1
  DO
    IF i>0 THEN Put(32) FI
    PrintI(tab(i))
  OD
  PrintE("]")
RETURN

PROC SattaloCycle(INT ARRAY tab INT size)
  INT i,j,tmp

  i=size-1
  WHILE i>0
  DO
    j=Rand(i)
    tmp=tab(i)
    tab(i)=tab(j)
    tab(j)=tmp
    i==-1
  OD
RETURN

PROC Test(INT ARRAY tab INT size)
  Print("Original data: ")
  PrintTable(tab,size)
  SattaloCycle(tab,size)
  Print("Shuffled data: ")
  PrintTable(tab,size)
  PutE()
RETURN

PROC Main()
  INT ARRAY a=[10 20 30],b=[11 12 13 14 15 16 17 18 19 20 21 22]

  Test(a,0)
  Test(a,1)
  Test(a,2)
  Test(a,3)
  Test(b,12)
RETURN
