CARD FUNC Gcd(CARD a,b)
  CARD tmp

  IF a<b THEN
    tmp=a a=b b=tmp
  FI

  WHILE b#0
  DO
    tmp=a MOD b
    a=b
    b=tmp
  OD
RETURN(a)

PROC Test(CARD a,b)
  CARD res

  res=Gcd(a,b)
  PrintF("GCD of %I and %I is %I%E",a,b,res)
RETURN

PROC Main()
  Test(48,18)
  Test(9360,12240)
  Test(17,19)
  Test(123,1)
  Test(0,0)
RETURN
