PROC MAIN()
 Byte Key=764

 Printe("Press Y or N to continue")

 key=255

 Do
  Until Key=43 or Key=35
 Od

 Print("You pressed ")
 If Key=43 then Printe("Yes") Fi
 If Key=35 then Printe("No ") Fi

RETURN
