CREATE OR REPLACE PROCEDURE FIZZBUZZ AS
  i NUMBER;
BEGIN

  FOR i in 1 .. 100 LOOP
    IF MOD(i, 15) = 0 THEN
      DBMS_OUTPUT.PUT_LINE('FizzBuzz');
    ELSIF MOD(i, 5) = 0 THEN
      DBMS_OUTPUT.PUT_LINE('Buzz');
    ELSIF MOD(i, 3) = 0 THEN
      DBMS_OUTPUT.PUT_LINE('Fizz');
    ELSE
      DBMS_OUTPUT.PUT_LINE(i);
    END IF;
  END LOOP;

END FIZZBUZZ;
