HAI 1.3

HOW IZ I CUBE YR X
    FOUND YR PRODUKT OF X AN PRODUKT OF X AN X
IF U SAY SO

I HAS A COUNT ITZ 0
IM IN YR LOOP UPPIN YR N TIL BOTH SAEM N AN 50
    BOTH SAEM 0 AN MOD OF N AN 10, O RLY?
        YA RLY, VISIBLE ""
    OIC
    COUNT R SUM OF COUNT AN I IZ CUBE YR N MKAY
    VISIBLE COUNT " "!
IM OUTTA YR LOOP
VISIBLE ""

KTHXBYE
