INCLUDE "H6:SIEVE.ACT"

INT FUNC NextPrime(INT p BYTE ARRAY primes)
  DO
    p==+1
  UNTIL primes(p)
  OD
RETURN (p)

PROC Main()
  DEFINE MAXNUM="200"
  BYTE ARRAY primes(MAXNUM+1)
  INT p1,p2,f

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAXNUM+1)

  p2=2
  DO
    p1=p2
    p2=NextPrime(p2,primes)
    f=p1*p2-p1-p2
    IF f<10000 THEN
      PrintI(f) Put(32)
    ELSE
      EXIT
    FI
  OD
RETURN
