sprintf('%s\n',...
    'line1 text',...
    '      line2 text',...
    '            line3 text',...
    '            line4 text')

sprintf('%s\n',...
    'Usage: thingy [OPTIONS]',...
    '      -h                        Display this usage message',...
    '      -H hostname               Hostname to connect to')
