BYTE Func IsStrangePlusNumber(INT i)
  BYTE ARRAY primes=[0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0]
  BYTE d,prev,first,sum

  prev=255
  first=1
  WHILE i#0
  DO
    d=i MOD 10
    IF prev#255 THEN
      sum=d+prev
      IF first=1 AND primes(sum)=0 THEN
        RETURN (0)
      FI
      first=0
    FI
    prev=d
    i==/10
  OD
  IF primes(sum)=0 THEN
    RETURN (0)
  FI
RETURN (1)

PROC Main()
  INT i,count=[0]

  FOR i=101 TO 499
  DO
    IF IsStrangePlusNumber(i) THEN
      PrintI(i) Put(32)
      count==+1
    FI
  OD
  PrintF("%E%EThere are %I strange plus numbers",count)
RETURN
