BYTE FUNC Not(BYTE a)
RETURN (a!$FF)

PROC Main()
  BYTE a=[127],b=[2],res

  res=a&b
  PrintF("%B AND %B = %B%E",a,b,res)

  res=a%b
  PrintF("%B OR %B = %B%E",a,b,res)

  res=a!b
  PrintF("%B XOR %B = %B%E",a,b,res)

  res=Not(a)
  PrintF("NOT %B = %B (by %B XOR $FF)%E",a,res,a)

  res=a RSH b
  PrintF("%B SHR %B = %B%E",a,b,res)

  res=a LSH b
  PrintF("%B SHL %B = %B%E",a,b,res)
RETURN
