INCLUDE "D2:PRINTF.ACT" ;from the Action! Tool Kit

BYTE FUNC IsPrime(CARD x)
  CARD i,max

  i=2 max=x/2
  WHILE i<=max
  DO
    IF x MOD i=0 THEN
      RETURN (0)
    FI
    i==+1
  OD
RETURN (1)

PROC Main()
  CARD x,count,sum
  CHAR ARRAY s(6)

  Put(125) PutE() ;clear the screen
  PrintF("%3S%5S%6S%E","i","p(i)","sum")
  count=0 sum=0
  FOR x=2 TO 999
  DO
    IF IsPrime(x) THEN
      count==+1
      IF (count&1)=1 THEN
        sum==+x
        IF IsPrime(sum) THEN
          StrC(count,s) PrintF("%3S",s)
          StrC(x,s) PrintF("%5S",s)
          StrC(sum,s) PrintF("%6S%E",s)
        FI
      FI
    FI
  OD
RETURN
