HAI 1.3

I HAS A X
VISIBLE "GIMMEH UR REEL NUMBAR:"
GIMMEH X
X IS NOW A NUMBAR
IM IN YR LOOP UPPIN YR ITERZ
    I HAS A XNEW ITZ PRODUKT OF 0.86 AN SUM OF X AN 3
    BOTH SAEM XNEW AN X, O RLY?
        YA RLY
            VISIBLE ":{XNEW} (:{ITERZ} ITERASHUNZ B4 KONVURJANCE)"
            GTFO
    OIC
    X R XNEW
IM OUTTA YR LOOP

KTHXBYE
