PROC PrintArray(INT ARRAY a INT size)
  INT i

  Put('[)
  FOR i=0 TO size-1
  DO
    IF i>0 THEN Put(' ) FI
    PrintI(a(i))
  OD
  Put(']) PutE()
RETURN

PROC CoctailShakerSort(INT ARRAY a INT size)
  INT begIdx,endIdx,newBegIdx,newEndIdx,i,tmp

  begIdx=0 endIdx=size-2
  WHILE begIdx<=endIdx
  DO
    newBegIdx=endIdx
    newEndIdx=begIdx
    i=begIdx
    WHILE i<=endIdx
    DO
      IF a(i)>a(i+1) THEN
        tmp=a(i) a(i)=a(i+1) a(i+1)=tmp
        newEndIdx=i
      FI
      i==+1
    OD
    endIdx=newEndIdx-1

    i=endIdx
    WHILE i>=begIdx
    DO
      IF a(i)>a(i+1) THEN
        tmp=a(i) a(i)=a(i+1) a(i+1)=tmp
        newBegIdx=i
      FI
      i==-1
    OD
    begIdx=newBegIdx+1
  OD
RETURN

PROC Test(INT ARRAY a INT size)
  PrintE("Array before sort:")
  PrintArray(a,size)
  CoctailShakerSort(a,size)
  PrintE("Array after sort:")
  PrintArray(a,size)
  PutE()
RETURN

PROC Main()
  INT ARRAY
    a(10)=[1 4 65535 0 3 7 4 8 20 65530],
    b(21)=[10 9 8 7 6 5 4 3 2 1 0
      65535 65534 65533 65532 65531
      65530 65529 65528 65527 65526],
    c(8)=[101 102 103 104 105 106 107 108],
    d(12)=[1 65535 1 65535 1 65535 1
      65535 1 65535 1 65535]

  Test(a,10)
  Test(b,21)
  Test(c,8)
  Test(d,12)
RETURN
