class Animal{
   //contents go here...
}
class Dog extends Animal{
   //contents go here...
}
class Cat extends Animal{
   //contents go here...
}
class Lab extends Dog{
   //contents go here...
}
class Collie extends Dog{
   //contents go here...
}
