PROC Main()
  INT a,b

  Print("Input value of a:") a=InputI()
  Print("Input value of b:") b=InputI()

  IF a<b THEN
    PrintF("%I is less than %I%E",a,b)
  FI
  IF a>b THEN
    PrintF("%I is greater than %I%E",a,b)
  FI
  IF a=b THEN
    PrintF("%I is equal to %I%E",a,b)
  FI
RETURN
