;; Shows a maze
(define (show-maze m)
  (match-define (maze N M tbl) m)
  (for ([i N]) (display "+---"))
  (displayln "+")
  (for ([j M])
    (display "|")
    (for ([i (- N 1)])
      (if (connected? tbl (list i j) (list (+ 1 i) j))
          (display "    ")
          (display "   |")))
    (display "   |")
    (newline)
    (for ([i N])
      (if (connected? tbl (list i j) (list i (+ j 1)))
          (display "+   ")
          (display "+---")))
    (displayln "+"))
  (newline))
