""" Handle commandline arguments and run ULM program """
function universallambdamachine(prog = "", input = "0", mode = "bit")
    inp = []
    program_bit_string = ""
    program_idx = 1
    input_bit_string = ""
    input_idx = 1
    bytemode = false

    """ Convert a boolean bit (0 or 1) into a lambda function (Church boolean). """
    function bit2lam(bit)
        return x0 -> x1 -> bit ? x1 : x0
    end

    """
        Convert a byte into a sequence of Church booleans (lambdas). This is done
        recursively, processing bits from most significant to least significant.
     """
    function byte2lam(bits, n)
        if n == 0
            # Base case: if no bits left, return an identity function for the list (empty list).
            return (args...) -> (y) -> y
        end
        # Recursively build the Church numeral:
        # ''z'' is a function that takes a bit and a tail of bits.
        # We apply ''z'' with the current bit (converted to Church boolean)
        # and the result of converting the rest of the bits.
        return z -> z(bit2lam((bits >> (n-1)) & 1))(byte2lam(bits, n-1))
    end

    """
        Lazily read input bits from the global ''input_bit_string'' and convert
        to a stream of Church booleans. Get more input from ''inp'' as needed.
    """
    function input_func(n) # renamed from 'input' to avoid conflict with Base.input
        # If the requested input index is beyond what's already read/stored
        if n >= length(inp)
            if input_idx <= length(input_bit_string)
                # Read a character from the input string and convert to a boolean bit.
                bit_char = input_bit_string[input_idx]
                if bit_char == '0'
                    bit_val = false
                elseif bit_char == '1'
                    bit_val = true
                else
                    error("Invalid character in input bit string: '$bit_char'. Only '0' or '1' allowed.")
                end
                input_idx += 1 # Move to the next bit in the input string
                # Push a lambda that represents the current bit and recursively calls for the next.
                push!(inp, z -> z(bit2lam(bit_val))(input_func(n+1)))
            else
                # If end of the input string is reached, push a lambda that represents an empty stream/end of input.
                push!(inp, (args...) -> (y) -> y)
            end
        end
        # Return the input element at the requested index (Julia uses 1-based indexing).
        return inp[n+1]
    end

    """ Convert a Church boolean back to a Julia Bool. """
    function lam2bit(lambit)
        # Applying the Church boolean:
        # ''lambit'' takes two arguments (true_branch, false_branch) and returns one of them.
        # Here, ''(args...) -> 0'' is the false_branch (returns 0).
        # ''(args...) -> 1'' is the true_branch (returns 1).
        # The final ''(0)'' forces the evaluation of the chosen branch.
        return lambit((args...) -> 0)((args...) -> 1)(0) # force suspension
    end

    """ Convert a Church numeral representing a sequence of bits back to a UInt8 byte. """
    function lam2byte(lambits, x)
        # ''lambits'' is a Church list, which takes a "cons" function and an "nil" value.
        # The "cons" function ''lambit -> lamtail -> ...'' takes the head bit and the rest of the list.
        # We apply this "cons" function to process each bit.
        # ''lam2bit(lambit)'' converts the current Church bit to 0 or 1.
        # ''2*x + lam2bit(lambit)'' accumulates the byte value.
        # The ''UInt8[x]'' is the "nil" value, which is returned when the list is empty.
        # This is a common pattern for folding over Church lists.
        return lambits(lambit -> lamtail -> (args...) -> lam2byte(lamtail, 2*x + lam2bit(lambit)))(UInt8[x])
    end

    """ Process the output stream generated by the lambda calculus program. """
    function output_func(prog) # renamed from 'output' to avoid conflict
        # ''prog'' is a Church list, which takes a "cons" function and an "nil" value.
        # The "cons" function ''c -> begin ... end'' processes the head element ''c'' (a Church bit/byte).
        # The "nil" value is ''(0)'', which is returned when the list is empty.
        return prog(c -> begin
            if bytemode != 0
                # If in byte mode, convert the Church byte ''c'' to a Julia byte and write it.
                write(stdout, lam2byte(c, 0))
            else
                # If in bit mode, convert the Church bit ''c'' to '1' or '0' and write it.
                write(stdout, lam2bit(c) != 0 ? b"1" : b"0")
            end
            # Return a function for the tail of the list, allowing recursive processing.
            return (tail) -> (args...) -> output_func(tail)
        end)(0)
    end

    """Read a single bit from the global ''program_bit_string''. """
    function getbit()
        if program_idx > length(program_bit_string)
            # If the end of the program string is reached unexpectedly, it indicates an error
            # in the program's binary encoding or an incomplete program.
            error("End of program bit string reached unexpectedly. Program might be incomplete or malformed.")
        end
        # Read a character from the program string and convert to a boolean bit.
        bit_char = program_bit_string[program_idx]
        if bit_char == '0'
            bit_val = false
        elseif bit_char == '1'
            bit_val = true
        else
            error("Invalid character in program bit string: '$bit_char'. Only '0' or '1' allowed.")
        end
        program_idx += 1 # Move to the next bit in the program string
        return bit_val ? 1 : 0 # Return 0 or 1
    end

    """ Parse the BLC program from the ''program_bit_string'' using ''getbit()''. """
    function program()
        if getbit() == 1 # Variable
            i = 0
            # Read ''1''s to determine the variable index (i.e., how many nested lambdas deep it is).
            while getbit() == 1
                i += 1
            end
            # Return a lambda that selects the (i+1)-th argument from its environment.
            # Julia uses 1-based indexing for ''args''.
            return (args...) -> args[i+1]
        elseif getbit() == 1 # Application (01)
            p = program() # Parse the function part
            q = program() # Parse the argument part
            # Return a lambda that applies ''p'' to a suspended version of ''q''.
            # ''p(args...)'' gets the function.
            # ''(arg -> q(args...)(arg))'' is a thunk that will evaluate ''q'' when called.
            return (args...) -> p(args...)(arg -> q(args...)(arg)) # suspend argument
        else # Abstraction (00)
            p = program() # Parse the body of the abstraction
            # Return a lambda that takes a new argument ''arg'' and extends the environment
            # for the body ''p'' by placing ''arg'' at the head of the argument list.
            return (args...) -> (arg) -> p(arg, args...) # extend environment with one more argument
        end
    end

    # if not function arguments, check for correct number of command-line arguments.
    if isempty(prog)
        if length(ARGS) < 2
            println("""
            Usage: julia program.jl <program_bit_string> <input_bit_string> [input_mode]")
                <program_bit_string>: A string of '0's and '1's representing the lambda calculus program.")
                <input_bit_string>: A string of '0's and '1's representing the data input to the program.")
                [input_mode]: Optional. 'byte' for byte-wise input (8 bits per byte), 'bit' for bit-wise,
                   one bit per character (default: bit).
            """)
            return
        end
        prog = ARGS[1]
        input = ARGS[2]
        length(ARGS) >= 3 && (mode = ARGS[3])
        program_bit_string = ARGS[1]
        input_bit_string = ARGS[2]
    else
        program_bit_string = prog
        input_bit_string = input
    end
    bytemode = mode == "byte" ? true : false
    prog = program()(0)
    output_func(prog(input_func(0)))
    println()
end

# Test a program that outputs its input except for the first bit.
universallambdamachine("0001100000100000", "100110011")
universallambdamachine()
