(let* ((min 1)
       (max 100)
       (number (+ (random (1+ (- max min))) min))
       guess done)
  (message "Guess the number between %d and %d" min max)
  (while (not done)
    (setq guess (read-number "Please enter a number "))
    (cond
     ((< guess number)
      (message "Too low!"))
     ((> guess number)
      (message "Too high!"))
     ((= guess number)
      (setq done t)
      (message "Well guessed!")))))
