INT FUNC SumDigits(INT num)
  INT res,a

  res=0
  WHILE num#0
  DO
    res==+num MOD 10
    num=num/10
  OD
RETURN (res)

BYTE Func IsValidNumber(INT num)
  CHAR ARRAY s(5),sub(5)
  INT sum,v,len,start

  sum=SumDigits(num)
  StrI(num,s)
  FOR len=1 TO s(0)
  DO
    FOR start=1 TO s(0)-len+1
    DO
      SCopyS(sub,s,start,start+len-1)
      IF ValI(sub)=sum THEN
        RETURN (1)
      FI
    OD
  OD
RETURN (0)

PROC Main()
  INT i,count=[0]

  FOR i=0 TO 999
  DO
    IF IsValidNumber(i) THEN
      PrintI(i) Put(32)
      count==+1
    FI
  OD
  PrintF("%E%EThere are %I numbers",count)
RETURN
