#main:# (
  REAL r=exp(pi)-pi;
  print((r,newline));
  printf(($g(-16,4)l$,-r));
  printf(($g(-16,4)l$,r));
  printf(($g( 16,4)l$,r));
  printf(($g( 16,4,1)l$,r));
  printf(($-dddd.ddddl$,-r));
  printf(($-dddd.ddddl$,r));
  printf(($+dddd.ddddl$,r));
  printf(($ddddd.ddddl$,r));
  printf(($zzzzd.ddddl$,r));
  printf(($zzzz-dd.ddddl$,-r));
  printf(($zzzz-dd.dddde-ddl$,-r));
  printf(($zz-d.dddde+ddl$,-r));
  printf(($4z-d.4de+4dl$,r))
)
