DEFINE ADC="$6D"
DEFINE CLC="$18"
DEFINE JSR="$20"
DEFINE LDA="$AD"
DEFINE RTS="$60"
DEFINE STA="$8D"

PROC Main()
  BYTE ARRAY buf(20)
  BYTE a=[19],b=[37],s
  CARD addr

  addr=buf
  Poke(addr,CLC) addr==+1
  Poke(addr,LDA) addr==+1
  PokeC(addr,@a) addr==+2
  Poke(addr,ADC) addr==+1
  PokeC(addr,@b) addr==+2
  Poke(addr,STA) addr==+1
  PokeC(addr,@s) addr==+2
  Poke(addr,RTS) addr==+1

  [JSR buf] ;run the machine code stored on buf

  PrintF("%B+%B=%B%E",a,b,s)
RETURN
