--#SET TERMINATOR @

SET SERVEROUTPUT ON@

BEGIN
 DECLARE VAL INTEGER;
 LOOP: WHILE (TRUE = TRUE) DO
  SET VAL = INTEGER(RAND() * 20);
  CALL DBMS_OUTPUT.PUT_LINE(VAL);
  IF (VAL = 10) THEN
   LEAVE LOOP;
  END IF;
  SET VAL = INTEGER(RAND() * 20);
  CALL DBMS_OUTPUT.PUT_LINE(VAL);
 END WHILE LOOP;
END @
