INT FUNC Encode(INT x CHAR ARRAY s)
  BYTE len,i
  CHAR tmp

  len=0 tmp=x
  WHILE tmp#0
  DO
    len==+1
    s(len)='0+(tmp&1)
    tmp==RSH 1
  OD
  FOR i=1 TO len RSH 1
  DO
    tmp=s(i) s(i)=s(len-i+1) s(len-i+1)=tmp
  OD
  FOR i=1 TO len
  DO
    s(i+len)=s(i)
  OD
  s(0)=len
RETURN (x LSH len+x)

PROC Main()
  CHAR ARRAY s(20)
  INT i=[1],res,count=[0]

  DO
    res=Encode(i,s)
    IF res>=1000 THEN
      EXIT
    FI
    Position((count&1)*15+2,count RSH 1+1)
    PrintF("%I: %S",res,s)
    i==+1 count==+1
  OD
RETURN
