PROC Main()
  BYTE x,y,size=[16]

  Graphics(0)
  PutE() PutE()

  y=size-1
  DO
    FOR x=1 TO y+2
    DO Put(' ) OD

    FOR x=0 TO size-y-1
    DO
      IF (x&y)=0 THEN
        Print("* ")
      ELSE
        Print("  ")
      FI
    OD
    PutE()

    IF y=0 THEN
      EXIT
    FI
    y==-1
  OD
