CARD EndProg ;required for ALLOCATE.ACT

INCLUDE "D2:ALLOCATE.ACT" ;from the Action! Tool Kit. You must type 'SET EndProg=*' from the monitor after compiling, but before running this program!

PROC Main()
  DEFINE PTR="CARD"
  BYTE i,nLines
  PTR ARRAY lines(256)
  CHAR ARRAY line(256),p

  AllocInit(0)
  Put(125) PutE()

  nLines=InputB()
  IF nLines=0 THEN RETURN FI

  FOR i=0 TO nLines-1
  DO
    InputS(line)
    p=Alloc(line(0)+1)
    MoveBlock(p,line,line(0)+1)
    lines(i)=p
  OD

  PutE()
  FOR i=0 TO nLines-1
  DO
    p=lines(i)
    PrintE(p)
  OD

  FOR i=0 TO nLines-1
  DO
    p=lines(i)
    Free(p,p(0)+1)
    lines(i)=0
  OD
  nLines=0
RETURN
