INCLUDE "H6:SIEVE.ACT"

BYTE FUNC NonDecreasingDigits(INT x)
  BYTE c,d,last

  c=0 last=9
  WHILE x#0
  DO
    d=x MOD 10
    IF d>last THEN
      RETURN (0)
    FI
    last=d
    x==/10
  OD
RETURN (1)

PROC Main()
  DEFINE MAX="999"
  BYTE ARRAY primes(MAX+1)
  INT i,count=[0]

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAX+1)
  FOR i=2 TO MAX
  DO
    IF primes(i)=1 AND NonDecreasingDigits(i)=1 THEN
      PrintI(i) Put(32)
      count==+1
    FI
  OD
  PrintF("%E%EThere are %I primes",count)
RETURN
