INCLUDE "H6:SIEVE.ACT"

DEFINE MAX="15999"
DEFINE MAXSQUARES="126"
BYTE ARRAY primes(MAX+1)
INT ARRAY squares(MAXSQUARES)

PROC CalcSquares()
  INT i

  FOR i=1 TO MAXSQUARES
  DO
    squares(i-1)=i*i
  OD
RETURN

INT FUNC FindNextQuadraticPrime(INT x)
  INT i,next

  FOR i=0 TO MAXSQUARES-1
  DO
    next=x+squares(i)
    IF next>MAX THEN
      RETURN (-1)
    FI
    IF primes(next) THEN
      RETURN (next)
    FI
  OD
RETURN (-1)

PROC Main()
  INT p=[2]

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAX+1)
  CalcSquares()
  WHILE p>0
  DO
    PrintI(p) Put(32)
    p=FindNextQuadraticPrime(p)
  OD
RETURN
