PROC Wait(BYTE frames)
  BYTE RTCLOK=$14
  frames==+RTCLOK
  WHILE frames#RTCLOK DO OD
RETURN

PROC Main()
  BYTE CH=$02FC ;Internal hardware value for last key pressed

  PrintE("Program is halted for 200 frames.")
  PrintE("Type character to fill the buffer.")
  Wait(200)
  PutE()

  DO
    IF CH=$FF THEN
      PrintE("The buffer is empty.")
      EXIT
    ELSE
      PrintF("The buffer stores internal key: %B.%E",CH)
      PrintE("Flush the buffer.")
      CH=$FF
    FI
  OD
RETURN
