   echo W=: lenword 9
roughcast
   echo P=: polybius ''
PV5M6Q
KR0391
4ZS7LA
FUT28E
GXOBYW
ICJDNH
   echo E=: P ADFGVX W 'ATTACKAT1200AM'
FFF FGF FFF GXD XDG FDGG XDX XXA GAD
   echo D=: P XVGFDA W E
ATTACKAT1200AM
