Math.e; (* e *)
Math.pi; (* pi *)
Math.sqrt x; (* square root *)
Math.ln x; (* natural logarithm--log base 10 also available (Math.log10) *)
Math.exp x; (* exponential *)
abs x; (* absolute value *)
floor x; (* floor *)
ceil x; (* ceiling *)
Math.pow (x, y); (* power *)
~ x; (* negation *)
