PROC Split(CHAR ARRAY s)
  BYTE i
  CHAR curr,last

  i=1 last=s(1)
  Put('")
  WHILE i<=s(0)
  DO
    curr=s(i)
    IF curr#last THEN
      Print(", ")
    FI
    Put(curr)
    last=curr
    i==+1
  OD
  Put('")
RETURN

PROC Test(CHAR ARRAY s)
  PrintF("Input: ""%S""%E",s)
  Print("Split: ") Split(s)
  PutE() PutE()
RETURN

PROC Main()
  Test("gHHH5YY++///\")
  Test("gHHH   5++,,,///\")
RETURN
