;;; Iterative Towers of Hanoi; translated from Tiny BASIC via PL/M
;;;

DEFINE NUMBER_OF_DISCS = "4"

PROC Main()

  INT d, n, x

  n = 1
  FOR d = 1 TO NUMBER_OF_DISCS DO
    n = n + n
  OD
  FOR x = 1 TO n - 1 DO
    ; as with Algol W, PL/M, Action! has bit and MOD operators
    Print( "Move disc on peg " )
    Put( '1 + (   ( x AND ( x - 1 ) )       MOD 3 ) )
    Print( " to peg " )
    Put( '1 + ( ( ( x OR  ( x - 1 ) ) + 1 ) MOD 3 ) )
    PutE()
  OD
RETURN
