PROC Increment(CHAR ARRAY src,dst)
  INT val

  val=ValI(src)
  val==+1
  StrI(val,dst)
RETURN

PROC Test(CHAR ARRAY src)
  CHAR ARRAY dst(10)
  Increment(src,dst)
  PrintF("%S+1=%S%E",src,dst)
RETURN

PROC Main()
  Test("0")
  Test("1")
  Test("9999")
  Test("-1")
  Test("-2")
  Test("-10000")
RETURN
