HAI 1.3

HOW IZ I STRREP YR S AN YR N
    I HAS A OUTPUT ITZ ""
    IM IN YR LOOP UPPIN YR M TIL BOTH SAEM N AN M
        OUTPUT R SMOOSH OUTPUT S MKAY
    IM OUTTA YR LOOP
    FOUND YR OUTPUT
IF U SAY SO

IM IN YR LOOP UPPIN YR N TIL BOTH SAEM N AN 8
    I HAS A REPUNIT ITZ I IZ STRREP YR 1 AN YR N MKAY
    SMOOSH REPUNIT 3 MKAY
    VISIBLE PRODUKT OF IT AN IT
IM OUTTA YR LOOP

KTHXBYE
