HAI 1.2
   I HAS A VAR1 ITZ A YARN BTW DECLARE A VARIABLE FOR LATER USE
   I HAS A VAR2 ITZ A YARN BTW DECLARE A VARIABLE FOR LATER USE
   VISIBLE "NUMBAH 1?"
   GIMMEH VAR1 BTW GET INPUT (NUMBER) INTO VARIABLE
   VISIBLE "NUMBAH 2?"
   GIMMEH VAR2 BTW GET INPUT (NUMBER) INTO VARIABLE
   VISIBLE SUM OF VAR1 AN VAR2
KTHXBYE
