PROC Strip(CHAR ARRAY text,chars,res)
  BYTE i,j,size,found
  CHAR c

  size=0
  FOR i=1 TO text(0)
  DO
    c=text(i) found=0
    FOR j=1 TO chars(0)
    DO
      IF c=chars(j) THEN
        found=1 EXIT
      FI
    OD
    IF found=0 THEN
      size==+1
      res(size)=c
    FI
  OD
  res(0)=size
RETURN

PROC Main()
  CHAR ARRAY
    text="She was a soul stripper. She took my heart!",
    chars="aei", result(255)

  Strip(text,chars,result)
  PrintE("String to be stripped:")
  PrintF("""%S""%E%E",text)
  PrintE("Characters to be stripped:")
  PrintF("""%S""%E%E",chars)
  PrintE("Stripped string:")
  PrintF("""%S""%E%E",result)
RETURN
