DEFINE PTR="CARD"

BYTE Func Equals(CHAR ARRAY a,b)
  BYTE i

  IF a(0)#b(0) THEN
    RETURN (0)
  FI

  FOR i=1 TO a(0)
  DO
    IF a(i)#b(i) THEN
      RETURN (0)
    FI
  OD
RETURN (1)

BYTE FUNC CommonLength(PTR ARRAY texts BYTE count)
  CHAR ARRAY t
  BYTE i,len

  IF count=0 THEN
    RETURN (0)
  FI

  len=255
  FOR i=0 TO count-1
  DO
    t=texts(i)
    IF t(0)<len THEN
      len=t(0)
    FI
  OD
RETURN (len)

PROC Suffix(PTR ARRAY texts BYTE count CHAR ARRAY res)
  CHAR ARRAY t(100)
  CHAR ARRAY tmp
  BYTE i,len,found

  IF count=1 THEN
    SCopy(res,texts(0))
    RETURN
  FI

  len=CommonLength(texts,count)
  WHILE len>0
  DO
    tmp=texts(0)
    SCopyS(res,tmp,tmp(0)-len+1,tmp(0))
    found=1
    FOR i=1 TO count-1
    DO
      tmp=texts(i)
      SCopyS(t,texts(i),tmp(0)-len+1,tmp(0))
      IF Equals(res,t)#1 THEN
        found=0 EXIT
      FI
    OD
    IF found THEN
      RETURN
    FI
    len==-1
  OD
  res(0)=0
RETURN

PROC Test(PTR ARRAY texts BYTE count)
  BYTE i
  CHAR ARRAY res(100)

  Suffix(texts,count,res)
  Print("lcs(")
  IF count>0 THEN
    FOR i=0 TO count-1
    DO
      PrintF("""%S""",texts(i))
      IF i<count-1 THEN
        Print(",")
      FI
    OD
  FI
  PrintF(")=""%S""%E",res)
RETURN

PROC Main()
  CHAR ARRAY
    t1="Sunday", t2="Monday", t3="Tuesday", t4="Wednesday",
    t5="Thursday", t6="Friday", t7="Saturday",
    t8="throne", t9="throne", t10="dungeon", t11="",
    t12="prefix", t13="suffix"
  PTR ARRAY texts(20)

  texts(0)=t1 texts(1)=t2 texts(2)=t3
  texts(3)=t4 texts(4)=t5 texts(5)=t6
  texts(6)=t7
  Test(texts,7)

  texts(0)=t8 texts(1)=t9
  Test(texts,2)

  texts(0)=t8 texts(1)=t10
  Test(texts,2)

  texts(0)=t8 texts(1)=t11 texts(2)=t9
  Test(texts,3)

  texts(0)=t10
  Test(texts,1)

  texts(0)=t11
  Test(texts,1)

  Test(texts,0)

  texts(0)=t12 texts(1)=t13
  Test(texts,2)
RETURN
