set samples {
    "Seventy-two dollars"
    "Seventy two dollars"
    "One Hundred and One Dalmatians"
    "A Hundred and One Dalmatians"
    "One Hundred One Dalmatians"
    "Hundred and One Dalmatians"
    "One Thousand and One Nights"
    "Two Thousand and One: A Space Odyssey"
    "Twenty Thirteen"
    "Nineteen Eighty-Four"
    "four billion, two hundred ninety-four million, nine hundred sixty-seven thousand, two hundred ninety five"
    "Nine quadrillion, seven trillion, one hundred ninety-nine billion, two hundred fifty-four million, seven hundred forty thousand, nine hundred ninety two"
    "Nine Hundred Ninety-Nine"
    "One Thousand One Hundred Eleven"
    "Eleven Hundred Eleven"
    "Eight Thousand Eight Hundred Eighty-Eight"
    "Eighty-Eight Hundred Eighty-Eight"
    "Seven Million Seven Hundred Seventy-Seven Thousand Seven Hundred Seventy-Seven"
    "Ninety-Nine Trillion Nine Hundred Ninety-Nine Billion Nine Hundred Ninety-Nine Million Nine Hundred Ninety-Nine Thousand Nine Hundred Ninety-Nine"
    "ninety-nine"
    "three hundred"
    "three hundred and ten"
    "one thousand, five hundred and one"
    "twelve thousand, six hundred and nine"
    "five hundred and twelve thousand, six hundred and nine"
    "forty-three million, one hundred and twelve thousand, six hundred and nine"
    "two billion, one hundred"
    "zero"
    "eight"
    "one hundred"
    "one hundred twenty three"
    "one thousand one"
    "ninety nine thousand nine hundred ninety nine"
    "one hundred thousand"
    "nine billion one hundred twenty three million four hundred fifty six thousand seven hundred eighty nine"
    "one hundred eleven billion one hundred eleven"
    "minus fifty six"
}
foreach s $samples {
    puts "$s => [name2num $s]"
}
