PROC Main()
  DEFINE PTR="CARD"
  DEFINE COUNT="20"
  CHAR ARRAY s(256)
  PTR ARRAY a(COUNT)
  BYTE i

  a(0)="It is certain."
  a(1)="It is decidedly so."
  a(2)="Without a doubt."
  a(3)="Yes - definitely."
  a(4)="You may rely on it."
  a(5)="As I see it, yes."
  a(6)="Most likely."
  a(7)="Outlook good."
  a(8)="Yes."
  a(9)="Signs point to yes."
  a(10)="Reply hazy, try again."
  a(11)="Ask again later."
  a(12)="Better not tell you now."
  a(13)="Cannot predict now."
  a(14)="Concentrate and ask again."
  a(15)="Don't count on it."
  a(16)="My reply is no."
  a(17)="My sources say no."
  a(18)="Outlook not so good."
  a(19)="Very doubtful."

  DO
    PrintE("Enter your question or blank to exit:")
    InputS(s)
    IF s(0)=0 THEN
      EXIT
    FI
    i=Rand(COUNT)
    PrintE(a(i))
    PutE()
  OD
RETURN
