PROC Main()
  DEFINE MAX="1000"
  INT ARRAY q(MAX+1)
  INT i

  q(1)=1 q(2)=1
  FOR i=3 TO MAX
  DO
    q(i)=q(i-q(i-1))+q(i-q(i-2))
  OD

  FOR i=1 TO 10
  DO
    PrintF("%I: %I%E",i,q(i))
  OD
  PrintF("%I: %I%E",MAX,q(MAX))
RETURN
