BYTE FUNC IsValidWord(CHAR ARRAY word)
  BYTE len

  len=word(0)
  IF len<=5 THEN RETURN (0) FI
  IF word(1)#word(len-2) THEN RETURN(0) FI
  IF word(2)#word(len-1) THEN RETURN(0) FI
  IF word(3)#word(len) THEN RETURN(0) FI
RETURN (1)

PROC FindWords(CHAR ARRAY fname)
  CHAR ARRAY line(256)
  CHAR ARRAY tmp(256)
  BYTE dev=[1]

  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    IF IsValidWord(line) THEN
      PrintE(line)
    FI
  OD
  Close(dev)
RETURN

PROC Main()
  CHAR ARRAY fname="H6:UNIXDICT.TXT"

  FindWords(fname)
RETURN
