(define (iterate phi n)
  (let ((phi1 (+ 1 (/ phi)))
        (n1 (+ n 1)))
    (if (<= (abs (- phi1 phi)) 1/100000)
        (values phi1 n1)
        (iterate phi1 n1))))

(call-with-values (lambda () (iterate 1 0))
  (lambda (phi n)
    (display "Result: ")
    (display phi)
    (display " (")
    (display (* 1.0 phi))
    (display ") after ")
    (display n)
    (display " iterations")
    (newline)
    (display "The error is approximately ")
    (display (- phi (* 0.5 (+ 1.0 (sqrt 5.0)))))
    (newline)))
