PROC Main()
  BYTE x,n,min=[1],max=[100]

  PrintF("Try to guess a number %B-%B: ",min,max)
  x=Rand(max-min+1)+min
  DO
    n=InputB()
    IF n<min OR n>max THEN
      Print("The input is incorrect. Try again: ")
    ELSEIF n<x THEN
      Print("My number is higher. Try again: ")
    ELSEIF n>x THEN
      Print("My number is lower. Try again: ")
    ELSE
      PrintE("Well guessed!")
      EXIT
    FI
  OD
RETURN
