#!/usr/local/bin/a68g --script #

[]STRING help = (
"Usage: thingy [OPTIONS]",
"     -h                        Display this usage message",
"     -H hostname               Hostname to connect to"
);

printf(($gl$,help,$l$));

printf(($gl$,
"The river was deep but I swam it, Janet.",
"The future is ours so let's plan it, Janet.",
"So please don't tell me to can it, Janet.",
"I've one thing to say and that's ...",
"Dammit. Janet, I love you."
))
