BYTE FUNC Count(CHAR ARRAY text CHAR c)
  BYTE i,n

  i=1 n=0
  FOR i=1 TO text(0)
  DO
    IF text(i)=c THEN
      n==+1
    FI
  OD
RETURN (n)

BYTE FUNC IsValidWord(CHAR ARRAY word)
  IF Count(word,'a)#0 THEN RETURN(0) FI
  IF Count(word,'e)<=3 THEN RETURN(0) FI
  IF Count(word,'i)#0 THEN RETURN(0) FI
  IF Count(word,'o)#0 THEN RETURN(0) FI
  IF Count(word,'u)#0 THEN RETURN(0) FI
RETURN (1)

PROC FindWords(CHAR ARRAY fname)
  CHAR ARRAY line(256)
  CHAR ARRAY tmp(256)
  BYTE dev=[1]

  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    IF IsValidWord(line) THEN
      PrintE(line)
    FI
  OD
  Close(dev)
RETURN

PROC Main()
  CHAR ARRAY fname="H6:UNIXDICT.TXT"

  FindWords(fname)
RETURN
