BYTE FUNC OnesCount(INT x)
  BYTE c,d

  c=0
  WHILE x#0
  DO
    d=x MOD 10
    IF d=1 THEN
      c==+1
    FI
    x==/10
  OD
RETURN (c)

PROC Main()
  INT i

  FOR i=0 TO 999
  DO
    IF OnesCount(i)=2 THEN
      PrintI(i) Put(32)
    FI
  OD
RETURN
