HAI 1.4

CAN HAS STRING?
I HAS A DNA ITZ SMOOSH ...
"CGTAAAAAATTACAACGTCCTTTGGCTATCTCTTAAACTCCTGCTAAATG" ...
"CTCGTGCTTTCCAATTATGTAAGCGTTCCGAGACGGGGTGGTCGATTCTG" ...
"AGGACAAAGGTCAAGATGGAGCGCATCGAACGCAATAAGGATCATTTGAT" ...
"GGGACGTTTCGTCGACAAAGTCTTGTTTCGAGAGTAACGGCTACCGTCTT" ...
"CGATTCTGCTTATAACACTATGTTCTTATGAAATGGATGTTCTGAGTTGG" ...
"TCAGTCCCAATGTGCGGGGTTTCTTTTAGTACGTCGGGAGTGGTATTATA" ...
"TTTAATTTTTCTATATAGCGATCTGTATTTAAGCAATTCATTTAGGTTAT" ...
"CGCCGCGATGCTCGGTTCGGACCGCCAAGCATCTGGCTCCACTGCTAGTG" ...
"TCCTAAATTTGAATGGCAAACACAAATAAGATTTAGCAATTCGTGTAGAC" ...
"GACCGGGGACTTGCATGATGGGAGCAGCTTTGTTAAACTACGAACGTAAT" MKAY

I HAS A L ITZ STRING IZ LEN YR DNA MKAY
I HAS A ACOUNT ITZ 0
I HAS A CCOUNT ITZ 0
I HAS A GCOUNT ITZ 0
I HAS A TCOUNT ITZ 0
IM IN YR LOOP UPPIN YR N TIL BOTH SAEM N AN L
    I HAS A PAD ITZ ""
    BOTH SAEM 0 AN N, O RLY?
        YA RLY, PAD R "  "
        MEBBE BOTH SAEM 50 AN N, PAD R " "
    OIC
    BOTH SAEM 0 AN MOD OF N AN 50, O RLY?
        YA RLY, VISIBLE ":)" PAD N ":: "!
    OIC
    I HAS A BASE ITZ STRING IZ AT YR DNA AN YR N MKAY
    VISIBLE BASE!
    BASE, WTF?
        OMG "A"
            ACOUNT R SUM OF ACOUNT AN 1
            GTFO
        OMG "C"
            CCOUNT R SUM OF CCOUNT AN 1
            GTFO
        OMG "G"
            GCOUNT R SUM OF GCOUNT AN 1
            GTFO
        OMG "T"
            TCOUNT R SUM OF TCOUNT AN 1
            GTFO
    OIC
IM OUTTA YR LOOP

VISIBLE ":):)BASE COUNTS"
VISIBLE "    A:: :{ACOUNT}"
VISIBLE "    C:: :{CCOUNT}"
VISIBLE "    G:: :{GCOUNT}"
VISIBLE "    T:: :{TCOUNT}"
VISIBLE "TOTAL:: :{L}"

KTHXBYE
