CARD FUNC Lcm(CARD a,b)
  CARD tmp,c

  IF a=0 OR b=0 THEN
   RETURN (0)
  FI

  IF a<b THEN
    tmp=a a=b b=tmp
  FI

  c=0
  DO
    c==+1
  UNTIL a*c MOD b=0
  OD
RETURN(a*c)

PROC Test(CARD a,b)
  CARD res

  res=Lcm(a,b)
  PrintF("LCM of %I and %I is %I%E",a,b,res)
RETURN

PROC Main()
  Test(4,6)
  Test(120,77)
  Test(24,8)
  Test(1,56)
  Test(12,0)
RETURN
