PROC PrintTable(BYTE ARRAY tab BYTE size)
  BYTE i

  FOR i=0 TO size-1
  DO
    PrintF("%B ",tab(i))
  OD
  PutE() PutE()
RETURN

PROC KnuthShuffle(BYTE ARRAY tab BYTE size)
  BYTE i,j,tmp

  i=size-1
  WHILE i>0
  DO
    j=Rand(i)
    tmp=tab(i)
    tab(i)=tab(j)
    tab(j)=tmp
    i==-1
  OD
RETURN

PROC Main()
  DEFINE LEN="20"
  BYTE ARRAY tab(LEN)
  BYTE i

  FOR i=1 TO LEN
  DO
    tab(i-1)=i
  OD
  FOR i=1 TO 5
  DO
    KnuthShuffle(tab,LEN)
    PrintTable(tab,LEN)
  OD
RETURN
