INCLUDE "H6:SIEVE.ACT"

BYTE FUNC SumOfDigits(INT x)
  BYTE s,d

  s=0
  WHILE x#0
  DO
    d=x MOD 10
    s==+d
    x==/10
  OD
RETURN (s)

PROC Main()
  DEFINE MAX="4999"
  BYTE ARRAY primes(MAX+1)
  INT i,count=[0]

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAX+1)
  FOR i=2 TO MAX
  DO
    IF primes(i)=1 AND SumOfDigits(i)=25 THEN
      PrintI(i) Put(32)
      count==+1
    FI
  OD
  PrintF("%E%EThere are %I primes",count)
RETURN
