;;; find some steady squares - numbers whose squares end in the number
;;; e.g. 376^2 = 141 376

PROC Main()
  CARD p     ; the number to square, with the final digit replaced by 0
  CARD n     ; the number to square
  CARD d10   ; 10^the number of digits in p, n
  CARD s     ; the square of n modulo d10
  CARD f     ; loop counter to choose 1, 5 or 6 as the final digit of q
  CARD front ; the first 2 digits of n
  CARD back  ; the last two digits of n

  d10 = 10
  FOR p = 0 TO 10000 STEP 10 DO
    IF p = d10 THEN
       d10 ==* 10
    FI
    FOR f = 1 TO 3 DO
      IF f = 1 THEN
        n = p + 1
      ELSEIF f = 2 THEN
        n = p + 5
      ELSE
        n = p + 6
      FI
      IF n <= 255 THEN
        s = ( n * n )
      ELSE
        front = n  /  100
        back  = n MOD 100
        s = ( back * back ) + ( 200 * ( ( front * back ) MOD 100 ) )
      FI
      s ==MOD d10
      IF s = n THEN
        Put(' ) PrintC( n )
      FI
    OD
  OD
RETURN
