begSec = time$("seconds")
graphic #g, 320,240
tics  = 320 * 240
for i = 1 to tics
    x = int((rnd(1) * 320) + 1)
    y = int((rnd(1) * 240) + 1)
    if int(x mod 2) then  #g "color black ; set "; x; " "; y else #g "color white ; set "; x; " "; y
next i
endSec = time$("seconds")
totSec = endSec - begSec
print "Seconds;";totSec;" Count:";tics;" Tics / sec:";tics/totSec;" fps:";1/totSec
render #g
#g "flush"
