[loop] cls                ' Clear screen
html "Click Y or N"                      ' no other options
      button #y, "Y", [Y]                '   they either click [Y]
      button #n, "N", [N]                '   or they click [N]
html "<br>";msg$                         ' print message showing what they entered
wait
[Y] msg$ = "You entered [Y]es": goto [loop]
[N] msg$ = "You entered [N]o" : goto [loop]
