DEFINE PRIMECOUNT="4"
BYTE ARRAY primedigits(PRIMECOUNT)=[2 3 5 7]

PROC PrintNum(BYTE ARRAY code BYTE count)
  BYTE i,c

  FOR i=0 TO count-1
  DO
    c=code(i)
    Put(primedigits(c)+'0)
  OD
RETURN

BYTE FUNC Sum(BYTE ARRAY code BYTE count)
  BYTE i,res,c

  res=0
  FOR i=0 TO count-1
  DO
    c=code(i)
    res==+primedigits(c)
  OD
RETURN (res)

PROC Init(BYTE ARRAY code BYTE count)
  Zero(code,count)
RETURN

BYTE FUNC Next(BYTE ARRAY code BYTE count)
  INT pos,c

  pos=count-1
  DO
    c=code(pos)+1
    IF c<PRIMECOUNT THEN
      code(pos)=c
      RETURN (1)
    FI
    code(pos)=0
    pos==-1
    IF pos<0 THEN
      RETURN (0)
    FI
  OD
RETURN (0)

PROC Main()
  DEFINE MAXDIG="6"
  BYTE ARRAY digits(MAXDIG)
  BYTE count,pos

  count=1 pos=0
  Init(count)
  DO
    IF Sum(digits,count)=13 THEN
      IF pos+count>=38 THEN
        pos=0 PutE()
      FI
      PrintNum(digits,count) Put(32)
      pos==+count+1
    FI
    IF Next(digits,count)=0 THEN
      count==+1
      IF count>MAXDIG THEN
        EXIT
      FI
      Init(count)
    FI
  OD
RETURN
