;;; draw a "mosaic matrix" - one with a 1 in the top-left and then
;;; alternating with another character vertically and horizontally

;;; draws a mosaic matrix with height and width = n
PROC drawMosaic( INT n )
  CARD i, j, one
  FOR i = 1 TO n DO
    one = i AND 1
    FOR j = 1 TO n DO
      Put(' )
      IF one = 1 THEN Put('1) ELSE Put('.) FI
      one = ( one + 1 ) AND 1
    OD
    PutE()
  OD
RETURN

PROC Main()
  drawMosaic( 6 )
  PutE()
  drawMosaic( 7 )
RETURN
