HAI 1.3

I HAS A CATALAN ITZ 1
IM IN YR LOOP UPPIN YR N TIL BOTH SAEM N AN 15
    VISIBLE CATALAN " "!
    CATALAN R ...
        QUOSHUNT OF ...
            PRODUKT OF ...
                CATALAN AN ...
                PRODUKT OF ...
                    2 AN ...
                    SUM OF ...
                        PRODUKT OF 2 AN N ...
                        AN 1 ...
            AN SUM OF N AN 2
IM OUTTA YR LOOP
VISIBLE ""

KTHXBYE
