> (hash-join ss 'name rs 'name)
(((#(age 27) #(name "Jonah") #(nemesis "Whales")))
 ((#(age 27) #(name "Jonah") #(nemesis "Spiders")))
 ((#(age 18) #(name "Alan") #(nemesis "Ghosts"))
  (#(age 28) #(name "Alan") #(nemesis "Ghosts")))
 ((#(age 18) #(name "Alan") #(nemesis "Zombies"))
  (#(age 28) #(name "Alan") #(nemesis "Zombies")))
 ((#(age 28) #(name "Glory") #(nemesis "Buffy"))))
