[1] (cat 'superclass)

#<Class:ANIMAL #x57094c8>
[2] (collie 'superclass)

#<Class:DOG #x57094c8>
[3] (animal 'superclass)

#<Class:OBJECT #x57094c8>
[4] (dog 'show)

Object is #<Class:DOG #x57094c8>, Class is #<Class:CLASS #x57094c8>
Instance variables:
  NAME = DOG
  MESSAGES = ()
  IVARS = ()
  CVARS = #<Environment #x5879788>
  SUPERCLASS = #<Class:ANIMAL #x57094c8>
  IVARCNT = 0
  IVARTOTAL = 0
#<Class:DOG #x57094c8>
