BYTE FUNC IsPalindrome(INT x BYTE base)
  CHAR ARRAY digits="0123456789abcdef",s(16)
  BYTE d,i,len

  len=0
  DO
    d=x MOD base
    len==+1
    s(len)=digits(d+1)
    x==/base
  UNTIL x=0
  OD
  s(0)=len

  FOR i=1 TO len/2
  DO
    IF s(i)#s(len-i+1) THEN
      RETURN (0)
    FI
  OD
RETURN (1)

PROC Main()
  INT i

  FOR i=0 TO 24999
  DO
    IF IsPalindrome(i,16)=1 AND IsPalindrome(i,4)=1 AND IsPalindrome(i,2)=1 THEN
      PrintI(i) Put(32)
    FI
  OD
RETURN
