HAI 1.3

I HAS A dog ITZ "Benjamin"
I HAS A Dog ITZ "Samba"
I HAS A DOG ITZ "Bernie"

EITHER OF DIFFRINT dog AN Dog AN DIFFRINT Dog AN DOG, O RLY?
    YA RLY, VISIBLE "TEH 3 DOGZ R NAEMD :{dog}, :{Dog}, AN :{DOG}."
    NO WAI, VISIBLE "THERE IZ JUST 1 DOG NAEMD :{DOG}."
OIC

KTHXBYE
