DEFINE COUNT="100"

PROC Main()
  BYTE ARRAY doors(COUNT+1)
  BYTE door,pass

  FOR door=1 TO COUNT
  DO
    doors(door)=0
  OD

  PrintE("Following doors are open:")
  FOR pass=1 TO COUNT
  DO
    FOR door=pass TO COUNT STEP pass
    DO
      doors(door)==!$FF
    OD
    IF doors(pass)=$FF THEN
      PrintB(pass) Put(32)
    FI
  OD
RETURN
