(define data '(#hash((name . "Lagos") (population . 21))
               #hash((name . "Cairo") (population .  15.2))
               #hash((name . "Kinshasa-Brazzaville") (population .  11.3))
               #hash((name . "Greater Johannesburg") (population .  7.55))
               #hash((name . "Mogadishu") (population .  5.85))
               #hash((name . "Khartoum-Omdurman") (population .  4.98))
               #hash((name . "Dar Es Salaam") (population .  4.7))
               #hash((name . "Alexandria") (population .  4.58))
               #hash((name . "Abidjan") (population .  4.4))
               #hash((name . "Casablanca") (population .  3.98))))
