DEFINE FIRST="12345"
DEFINE SECOND="54321"
DEFINE PTR="CARD"

PROC Main()
  PTR base,copy=base

  PrintF("Address of base variable: %H%E",@base)
  PrintF("Address of copy variable: %H%E",@copy)
  PutE()

  PrintF("Assign %U value to base variable%E",FIRST)
  base=FIRST
  PrintF("Value of base variable: %U%E",base)
  PrintF("Value of copy variable: %U%E",copy)
  PutE()

  PrintF("Assign %U value to base variable%E",SECOND)
  base=SECOND
  PrintF("Value of base variable: %U%E",base)
  PrintF("Value of copy variable: %U%E",copy)
RETURN
