;;; Find numbers n such that n + n+1 is prime
;;; Library: Action! Sieve of Eratosthenes
INCLUDE "H6:SIEVE.ACT"

PROC Main()
  DEFINE MAX_PRIME = "255"

  BYTE ARRAY primes(MAX_PRIME)
  CARD n, n1, count

  Sieve(primes,MAX_PRIME)

  count = 0;
  n1 = 1
  WHILE count < 20 DO
    n = n1
    n1 ==+ 1
    IF primes( n + n1 ) THEN
      count ==+ 1
      PrintF( "%2U: %2U + %2U = %2U%E", count, n, n1, n + n1 )
    FI
  OD

RETURN
