PROC PrintFactors(CARD a)
  BYTE notFirst
  CARD p

  IF a=1 THEN
    PrintC(a) RETURN
  FI

  p=2 notFirst=0
  WHILE p<=a
  DO
    IF a MOD p=0 THEN
      IF notFirst THEN
        Put('x)
      FI
      notFirst=1
      PrintC(p)
      a==/p
    ELSE
      p==+1
    FI
  OD
RETURN

PROC Main()
  CARD i

  FOR i=1 TO 1000
  DO
    PrintC(i) Put('=)
    PrintFactors(i)
    PutE()
  OD
RETURN
