PROC Main()
  BYTE p,s,f

  PrintE("P S F")
  FOR p=2 TO 6 STEP 2
  DO
    FOR s=1 TO 7
    DO
      FOR f=1 TO 7
      DO
        IF p#s AND p#f AND s#f AND p+s+f=12 THEN
          PrintF("%B %B %B%E",p,s,f)
        FI
      OD
    OD
  OD
RETURN
