HAI 1.3

I HAS A N ITZ 1
IM IN YR LOOP UPPIN YR COUNT TIL BOTH SAEM N BIGGR OF N AN 1000
    BOTH SAEM N AN BIGGR OF N AN 100, O RLY?
        YA RLY, VISIBLE N " "!
    OIC
    N R SUM OF N AN PRODUKT OF 8 AN COUNT
IM OUTTA YR LOOP
VISIBLE ""

KTHXBYE
