INT FUNC CalcSum(CHAR ARRAY s)
  INT sum,i
  CHAR ARRAY tmp(100)

  sum=ValI(s)
  FOR i=1 TO s(0)
  DO
    IF s(i)=32 THEN EXIT FI
  OD
  SCopyS(tmp,s,i,s(0))
  sum==+ValI(tmp)
RETURN (sum)

PROC Main()
  BYTE i,nLines
  INT ARRAY sums(256)
  CHAR ARRAY line(256)

  nLines=InputB()
  IF nLines=0 THEN RETURN FI

  FOR i=0 TO nLines-1
  DO
    InputS(line)
    sums(i)=CalcSum(line)
  OD

  PutE()
  FOR i=0 TO nLines-1
  DO
    PrintIE(sums(i))
  OD
RETURN
