HAI 1.3

I HAS A X
I HAS A Y
VISIBLE "GIMMEH A NUMBR:"
GIMMEH X
X IS NOW A NUMBR
VISIBLE "GIMMEH ANOTHR NUMBR:"
GIMMEH Y
Y IS NOW A NUMBR

BOTH SAEM X AN Y, O RLY?
    YA RLY, VISIBLE ":{X} IZ EQUAL TO :{Y}"
    MEBBE DIFFRINT X AN SMALLR OF X AN Y
        VISIBLE ":{X} IZ GREATR THN :{Y}"
    MEBBE DIFFRINT X AN BIGGR OF X AN Y
        VISIBLE ":{X} IZ LESS THN :{Y}"
OIC

KTHXBYE
