DEFINE MAXSIZE="100"

PROC PrintArray(INT ARRAY a INT size)
  INT i

  Put('[)
  FOR i=0 TO size-1
  DO
    IF i>0 THEN Put(' ) FI
    PrintI(a(i))
  OD
  Put(']) PutE()
RETURN

PROC CountingSort(INT ARRAY a INT size,min,max)
  INT ARRAY count(MAXSIZE)
  INT n,i,num,z

  n=max-min+1
  FOR i=0 TO n-1
  DO count(i)=0 OD

  FOR i=0 TO size-1
  DO
    num=a(i)
    count(num-min)==+1
  OD

  z=0
  FOR i=min TO max
  DO
    WHILE count(i-min)>0
    DO
      a(z)=i
      z==+1
      count(i-min)==-1
    OD
  OD
RETURN

PROC Test(INT ARRAY a INT size,min,max)
  PrintE("Array before sort:")
  PrintArray(a,size)
  CountingSort(a,size,min,max)
  PrintE("Array after sort:")
  PrintArray(a,size)
  PutE()
RETURN

PROC Main()
  INT ARRAY
    a(10)=[1 4 65535 0 3 7 4 8 20 65530],
    b(21)=[10 9 8 7 6 5 4 3 2 1 0
      65535 65534 65533 65532 65531
      65530 65529 65528 65527 65526],
    c(8)=[101 102 103 104 105 106 107 108],
    d(12)=[1 65535 1 65535 1 65535 1
      65535 1 65535 1 65535]

  Test(a,10,-6,20)
  Test(b,21,-10,10)
  Test(c,8,101,108)
  Test(d,12,-1,1)
RETURN
