INCLUDE "D2:REAL.ACT" ;from the Action! Tool Ki

PROC Main()
  REAL c,rnom,rden
  BYTE n,nom,den

  Put(125) PutE() ;clear the screen
  IntToReal(1,c)

  FOR n=1 TO 15
  DO
    nom=(n LSH 1-1) LSH 1
    den=n+1
    IntToReal(nom,rnom)
    IntToReal(den,rden)
    RealMult(c,rnom,c)
    RealDiv(c,rden,c)
    PrintF("C(%B)=",n) PrintRE(c)
  OD
RETURN
