INCLUDE "H6:SIEVE.ACT"

BYTE Func IsErdosPrime(INT x BYTE ARRAY primes)
  INT k,f

  IF primes(x)=0 THEN
    RETURN (0)
  FI

  k=1 f=1
  WHILE f<x
  DO
    IF primes(x-f) THEN
      RETURN (0)
    FI
    k==+1
    f==*k
  OD
RETURN (1)

PROC Main()
  DEFINE MAX="2499"
  BYTE ARRAY primes(MAX+1)
  INT i,count=[0]

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAX+1)
  FOR i=2 TO MAX
  DO
    IF IsErdosPrime(i,primes) THEN
      PrintI(i) Put(32)
      count==+1
    FI
  OD
  PrintF("%E%EThere are %I Erdos primes",count)
RETURN
