PROC Main()
  INT i

  FOR i=-1 TO 1
  DO
    IF i<0 THEN
      PrintF("%I is less than zero%E",i)
    ELSEIF i>0 THEN
      PrintF("%I is greater than zero%E",i)
    ELSE
      PrintF("%I is zero%E",i)
    FI
  OD
RETURN
