INCLUDE "D2:REAL.ACT" ;from the Action! Tool Ki

DEFINE PTR="CARD"
DEFINE REALSIZE="6"

PTR FUNC GetItemAddr(PTR buf BYTE i)
RETURN (buf+REALSIZE*i)

PROC Main()
  DEFINE COUNT="15"
  BYTE ARRAY buf(102) ;(COUNT+2)*REALSIZE
  REAL POINTER r1,r2
  REAL c
  BYTE i,j

  Put(125) PutE() ;clear the screen

  r1=GetItemAddr(buf,1)
  IntToReal(1,r1)

  FOR i=1 TO COUNT
  DO
    j=i+1
    WHILE j>=2
    DO
      r1=GetItemAddr(buf,j)
      r2=GetItemAddr(buf,j-1)
      RealAdd(r1,r2,r1) ;t(j)==+t(j-1)
      j==-1
    OD
    r1=GetItemAddr(buf,i)
    r2=GetItemAddr(buf,i+1)
    RealAssign(r1,r2) ;t(i+1)=t(i)

    j=i+2
    WHILE j>=2
    DO
      r1=GetItemAddr(buf,j)
      r2=GetItemAddr(buf,j-1)
      RealAdd(r1,r2,r1) ;t(j)==+t(j-1)
      j==-1
    OD
    r1=GetItemAddr(buf,i)
    r2=GetItemAddr(buf,i+1)
    RealSub(r2,r1,c) ;c=t(i+1)-t(i)
    PrintF("C(%B)=",i) PrintRE(c)
  OD
RETURN
