INT FUNC Gcd(INT a,b)
  INT tmp

  IF a<b THEN
    tmp=a a=b b=tmp
  FI

  WHILE b#0
  DO
    tmp=a MOD b
    a=b b=tmp
  OD
RETURN (a)

PROC Test(INT a,b)
  CHAR ARRAY s0="not ",s1="",s

  IF Gcd(a,b)=1 THEN
    s=s1
  ELSE
    s=s0
  FI
  PrintF("%I and %I are %Scoprimes%E",a,b,s)
RETURN

PROC Main()
  Test(21,15)
  Test(17,23)
  Test(36,12)
  Test(18,29)
  Test(60,15)
RETURN
