PROC PrintOctal(CARD v)
  CHAR ARRAY a(6)
  BYTE i=[0]

  DO
    a(i)=(v&7)+'0
    i==+1
    v=v RSH 3
  UNTIL v=0
  OD

  DO
    i==-1
    Put(a(i))
  UNTIL i=0
  OD
RETURN

PROC Main()
  CARD i=[0]

  DO
    PrintF("decimal=%U octal=",i)
    PrintOctal(i) PutE()
    i==+1
  UNTIL i=0
  OD
RETURN
