PROC Main()
  BYTE ROWCRS=$0054 ;Current cursor row
  CARD COLCRS=$0055 ;Current cursor column
  CARD width
  BYTE height

  Graphics(0)
  Position(0,0) ;go to the top-left corner
  Put(28) Put(30) ;go up and left - the bottom-right corner
  width=COLCRS+1
  height=ROWCRS+1

  Position(2,1)
  PrintF("Number of colums: %U%E",width)
  PrintF("Number of rows: %B%E",height)
RETURN
