CREATE TABLE Address (
    addrID      Integer         generated by default as identity,
    addrStreet  Varchar(50)     not null,
    addrCity    Varchar(25)     not null,
    addrState   Char(2)         not null,
    addrZIP     Char(10)        not null
);
