   a:4 5#20?13   / create a random 4 x 5 matrix
(12 7 12 4 3
 6 3 7 4 7
 3 8 3 1 2
 2 12 6 4 1)

   ,/a           / flatten to array
12 7 12 4 3 6 3 7 4 7 3 8 3 1 2 2 12 6 4 1

   ?,/a          / distinct elements
12 7 4 3 6 8 1 2

   ?"chthonic eleemosynary paronomasiac"
"chtoni elmsyarp"

   ?("this";"that";"was";"that";"was";"this")
("this"
 "that"
 "was")

   0 1 1 2 0 *\: 0 1 2
(0 0 0
 0 1 2
 0 1 2
 0 2 4
 0 0 0)

   ?0 1 1 2 0 *\: 0 1 2
(0 0 0
 0 1 2
 0 2 4)
