DEFINE ROW_COUNT="4"
DEFINE COL_COUNT="3"

PROC Main()
  CHAR ARRAY headers=[0 'X 'Y 'Z]
  BYTE row,col
  INT v

  PrintE("<html>")
  PrintE("<head></head>")
  PrintE("<body>")
  PrintE("<table border=1>")
  PrintE("<thead align=""center"">")

  Print("<tr><th></th>")
  FOR col=1 TO COL_COUNT
  DO
    PrintF("<th>%C</th>",headers(col))
  OD
  PrintE("</tr>")
  PrintE("</thead>")
  PrintE("<tbody align=""right"">")

  FOR row=1 TO ROW_COUNT
  DO
    PrintF("<tr><th>%B</th>",row)
    FOR col=1 TO COL_COUNT
    DO
      v=800+Rand(0)*5
      PrintF("<td>%I</td>",v)
    OD
    PrintE("</tr>")
  OD
  PrintE("</tbody>")
  PrintE("</table>")
  PrintE("</body>")
  PrintE("</html>")
RETURN
