;If the input is an array, the output has the same dimensions etc as the input:
x = !dpi/[[2,3],[4,5],[6,7]] ; !dpi is a read-only sysvar = 3.1415...
print,sin(x)

;outputs:
;      1.0000000      0.86602540
;      0.70710678      0.58778525
;      0.50000000      0.43388374
