; the trig functions receive and emit radians:
print, rad, sin(rad), asin(sin(rad))
print, cos(rad), acos(cos(rad))
print, tan(rad), atan(tan(rad))        ; etc

; prints the following:
; 0.610865     0.573576     0.610865
; 0.819152     0.610865
; 0.700208     0.610865
