INT FUNC Power(INT a,b)
  INT i,res

  res=1
  FOR i=1 TO b
  DO
    res==*a
  OD
RETURN (res)

PROC Main()
  DEFINE BASE="10"
  DEFINE N="2"
  INT i,max,count,total,perc

  max=Power(BASE,N)
  count=0 total=0
  FOR i=1 TO max
  DO
    total==+1
    IF i MOD (BASE-1)=(i*i) MOD (BASE-1) THEN
      count==+1
      PrintI(i) Put(32)
    FI
  OD
  perc=100-100*count/total
  PrintF("%E%ETrying %I numbers instead of %I numbers saves %I%%",count,total,perc)
RETURN
