CHAR ARRAY line(256)

BYTE FUNC ConsonantsCount(CHAR ARRAY word)
  BYTE len,i,c,count
  BYTE ARRAY chars(128)

  len=word(0)
  IF len<=10 THEN RETURN (0) FI

  SetBlock(chars,128,0)
  count=0
  FOR i=1 TO len
  DO
    c=word(i)
    IF c#'a AND c#'e AND c#'i AND c#'o AND c#'u THEN
      IF chars(c) THEN RETURN (0) FI
      chars(c)=1
      count==+1
    FI
  OD
RETURN (count)

BYTE FUNC FindMostConsonants(CHAR ARRAY fname)
  BYTE max,count,dev=[1]

  max=0
  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    count=ConsonantsCount(line)
    IF max<count THEN
      max=count
    FI
  OD
  Close(dev)
RETURN (max)

PROC FindWords(CHAR ARRAY fname BYTE n)
  BYTE count,dev=[1]

  Close(dev)
  Open(dev,fname,4)
  WHILE Eof(dev)=0
  DO
    InputSD(dev,line)
    count=ConsonantsCount(line)
    IF count=n THEN
      Print(line) Put(32)
    FI
  OD
  Close(dev)
  PutE() PutE()
RETURN

PROC Main()
  CHAR ARRAY fname="H6:UNIXDICT.TXT"
  BYTE i,max

  PrintE("Finding the most consonants...")
  PutE()
  max=FindMostConsonants(fname)

  i=max
  WHILE i>=max-1
  DO
    PrintF("%B consonants:%E",i)
    FindWords(fname,i)
    i==-1
  OD
RETURN
