PROC Test(INT max,angle,coeff)
  BYTE count,a,b,c

  PrintF("gamma=%B degrees:%E",angle)
  count=0
  FOR a=1 TO max
  DO
    FOR b=1 TO a
    DO
      FOR c=1 TO max
      DO
        IF a*a+b*b-coeff*a*b=c*c THEN
          PrintF("(%B,%B,%B) ",a,b,c)
          count==+1
        FI
      OD
    OD
  OD
  PrintF("%Enumber of triangles is %B%E%E",count)
RETURN

PROC Main()
  Test(13,90,0)
  Test(13,60,1)
  Test(13,120,-1)
RETURN
