Squeeze ← (≠∨1»⊢≠«)/⊢

> ⊢‿Squeeze {(⊣∾(≠⋈"<<<"⊸∾∘∾⟜">>>")∘𝕏)´𝕨}⌜˜ ⟨
  'e'‿"The better the 4-wheel drive, the further you'll be from help when ya get stuck!"
  's'‿"headmistressship"
  ' '‿""
  '-'‿"""If I were two-faced, would I be wearing this one?"" --- Abraham Lincoln "
  '7'‿"..1111111111111111111111111111111111111111111111111111111111111117777888"
  '.'‿"I never give 'em hell, I just tell the truth, and they think it's hell. "
⟩ ∾ " -r" ⋈⚇0‿1 ¯72↑"--- Harry S Truman  "
