PROC Main()
  DEFINE MAX="1000"
  INT ARRAY ulam(MAX)
  INT uCount,n,count,x,y
  BYTE flag

  ulam(0)=1 ulam(1)=2 uCount=2
  PrintI(ulam(0)) Put(32) PrintI(ulam(1))
  n=3
  WHILE uCount<MAX
  DO
    flag=0 count=0
    FOR x=0 TO uCount-2
    DO
      FOR y=x+1 TO uCount-1
      DO
        IF ulam(x)+ulam(y)=n THEN
          flag=1 count==+1
        FI
      OD
    OD
    IF flag=1 AND count=1 THEN
      ulam(uCount)=n uCount==+1
      Put(32) PrintI(n)
    FI
    n==+1
  OD
RETURN
