HAI 1.3

HOW IZ I BINOMIAL YR N AN YR K
    I HAS A RESULT ITZ 1
    IM IN YR LOOP UPPIN YR M TIL BOTH SAEM M AN K
        RESULT R QUOSHUNT OF PRODUKT OF RESULT AN DIFF OF N AN M AN SUM OF M AN 1
    IM OUTTA YR LOOP
    FOUND YR RESULT
IF U SAY SO

VISIBLE I IZ BINOMIAL YR 5 AN YR 3 MKAY

KTHXBYE
