;;; draw a matrix with 1s on the diagonals and 0s elsewhere

;;; draws a matrix with height and width = n with 1s on the diagonals
PROC drawDiagonals( INT n )
  CARD i, j, r
  r = n
  FOR i = 1 TO n DO
    FOR j = 1 TO n DO
      Put(' )
      IF j = i OR j = r THEN Put('1) ELSE Put('0) FI
    OD
    PutE()
    r ==- 1
  OD
RETURN

PROC Main()
  drawDiagonals( 6 )
  PutE()
  drawDiagonals( 7 )
RETURN
