INCLUDE "H6:SIEVE.ACT"

PROC Main()
  DEFINE MAX="5499"
  BYTE ARRAY primes(MAX+1)
  INT i,count=[0]

  Put(125) PutE()
  Sieve(primes,MAX+1)
  FOR i=2 TO MAX-6
  DO
    IF primes(i)=1 AND primes(i+2)=1 AND (primes(i+6))=1 THEN
      PrintF("(%I %I %I) ",i,i+2,i+6)
      count==+1
    FI
  OD
  PrintF("%E%EThere are %I prime triplets",count)
RETURN
