PROC Wait(BYTE frames)
  BYTE RTCLOK=$14
  frames==+RTCLOK
  WHILE frames#RTCLOK DO OD
RETURN

PROC Main()
  CHAR ARRAY spin="|/-\"
  BYTE i,
    CH=$02FC, ;Internal hardware value for last key pressed
    CRSINH=$02F0 ;Controls visibility of cursor

  Print("Press any key to exit...")
  CRSINH=1 ;hide cursor
  i=1
  WHILE CH=$FF
  DO
    Put(spin(i))
    Put(30) ;move cursor left
    i==+1
    IF i>spin(0) THEN
      i=1
    FI
    Wait(5)
  OD
  CH=$FF
  CRSINH=0 ;show cursor
RETURN
