CARD FUNC SumDigits(CARD num,base)
  CARD res,a

  res=0
  WHILE num#0
  DO
    res==+num MOD base
    num=num/base
  OD
RETURN(res)

PROC Main()
  CARD ARRAY data=[
      1 10  1234 10  $FE 16  $F0E 16
      $FF 2  0 2  2186 3  2187 3]
  BYTE i
  CARD num,base,res

  FOR i=0 TO 15 STEP 2
  DO
    num=data(i)
    base=data(i+1)
    res=SumDigits(num,base)
    PrintF("num=%U base=%U sum=%U%E",num,base,res)
  OD
RETURN
