INCLUDE "H6:SIEVE.ACT"

PROC Main()
  DEFINE MAXPRIME="29"
  DEFINE MAX="99"
  BYTE ARRAY primes(MAX+1)
  BYTE n,m,p,c
  INT count=[0]

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAX+1)
  c=0
  FOR n=2 TO MAXPRIME-2
  DO
    IF primes(n) THEN
      FOR m=n+1 TO MAXPRIME-1
      DO
        IF primes(m) THEN
          FOR p=m+1 TO MAXPRIME
          DO
            IF primes(p)=1 AND primes(n+m+p)=1 THEN
              PrintF("%I+%I+%I=%I ",n,m,p,n+m+p)
              count==+1 c==+1
              IF c=3 THEN
                c=0 PutE()
              FI
            FI
          OD
        FI
      OD
    FI
  OD
  PrintF("%EThere are %I prime triplets",count)
RETURN
