PROC Test(BYTE v)
  PrintF("Variable v has value %B%E",v)
  IF v THEN
    PrintE("Condition IF v is satisfied.")
  ELSE
    PrintE("Condition IF v is not satisfied.")
  FI
  IF v=0 THEN
    PrintE("Condition IF v=0 is satisfied.")
  ELSE
    PrintE("Condition IF v=0 is not satisfied.")
  FI
  IF v<>0 THEN
    PrintE("Condition IF v<>0 is satisfied.")
  ELSE
    PrintE("Condition IF v<>0 is not satisfied.")
  FI
  IF v#0 THEN
    PrintE("Condition IF v#0 is satisfied.")
  ELSE
    PrintE("Condition IF v#0 is not satisfied.")
  FI
  PutE()
RETURN

PROC Main()
  Test(0)
  Test(1)
  Test(86)
RETURN
