import java.util.ArrayList;
import java.util.List;

public final class TheSieveOfSundaram {

	public static void main(String[] args) {
		List<Integer> primes = sieveOfSundaram(16_000_000);
		System.out.println("The first 100 odd primes generated by the Sieve of Sundaram:");
		for ( int i = 0; i < 100; i++ ) {
			System.out.print(String.format("%3d%s", primes.get(i), ( i % 10 == 9 ? "\n" :" " )));
		}
		System.out.println();
		System.out.println("The 1_000_000th Sundaram prime is " + primes.get(1_000_000 - 1));
	}
	
	private static List<Integer> sieveOfSundaram(int limit) {
		List<Integer> primes = new ArrayList<Integer>();
		if ( limit < 3 ) {
			return primes;
		}
		
		final int k = ( limit - 3 ) / 2 + 1;
		boolean[] marked = new boolean[k];
		for ( int i = 0; i < ( (int) Math.sqrt(limit) - 3 ) / 2 + 1; i++ ) {
			int p = 2 * i + 3;
			int s = ( p * p - 3 ) / 2;
            for ( int j = s; j < k; j += p ) {
				marked[j] = true;
            }				
		}
		
		for ( int i = 0; i < k; i++ ) {
	        if ( ! marked[i] ) {
	        	primes.add(2 * i + 3);
	        }
	    }
	    return primes;
	}

}
