INCLUDE "H6:SIEVE.ACT"

INT FUNC CountDivisors(INT x)
  INT i,max,count

  count=2 i=2 max=x
  WHILE i<max
  DO
    IF x MOD i=0 THEN
      max=x/i
      IF i<max THEN
        count==+2
      ELSEIF i=max THEN
        count==+1
      FI
    FI
    i==+1
  OD
RETURN (count)

PROC Main()
  DEFINE MAXNUM="999"
  BYTE ARRAY primes(MAXNUM+1)

  INT i,count

  Put(125) PutE() ;clear the screen
  Sieve(primes,MAXNUM+1)
  FOR i=2 TO MAXNUM
  DO
    IF primes(i)=0 THEN
      count=CountDivisors(i)
      IF count>2 AND primes(count)=1 THEN
        PrintF("%I has %I divisors%E",i,count)
      FI
    FI
  OD
RETURN
