PROC Main()
  BYTE
    CH=$02FC, ;Internal hardware value for last key pressed
    COLOR0=$02C4,COLOR1=$02C5,COLOR2=$02C6,COLOR4=$02C8
  CARD i

  Graphics(8+16)
  COLOR4=$04 ;gray
  COLOR1=$00 ;black
  COLOR2=$0F ;white

  FOR i=0 TO 319
  DO
    Color=i MOD 2
    Plot(i,0) DrawTo(i,47)

    Color=i/2 MOD 2
    Plot(i,48) DrawTo(i,95)

    Color=i/3 MOD 2
    Plot(i,96) DrawTo(i,143)

    Color=i/4 MOD 2
    Plot(i,144) DrawTo(i,191)
  OD

  DO UNTIL CH#$FF OD
  CH=$FF
RETURN
