latten$ = "[[1], 2, [[3,4], 5], [[[]]], [[[6]]], 7, 8 []]"

i = instr(flatten$,"[")
while i > 0
 flatten$ = left$(flatten$,i-1) + mid$(flatten$,i+1)
 i = instr(flatten$,"]")
 flatten$ = left$(flatten$,i-1) + mid$(flatten$,i+1)
 i = instr(flatten$," ")
 flatten$ = left$(flatten$,i-1) + mid$(flatten$,i+1)
 i = instr(flatten$,",,")
 flatten$ = left$(flatten$,i-1) + mid$(flatten$,i+1)
 i = instr(flatten$,"[")
wend

print flatten$
