INCLUDE "D2:CHARTEST.ACT" ;from the Action! Tool Kit

PROC Main()
  CHAR ARRAY lower(128),upper(128)
  CHAR c
  BYTE lowerLen,upperLen

  Put(125) PutE() ;clear screen

  lowerLen=0
  upperLen=0
  FOR c=0 TO 127
  DO
    IF IsLower(c) THEN
      lowerLen==+1
      lower(lowerLen)=c
    ELSEIF IsUpper(c) THEN
      upperLen==+1
      upper(upperLen)=c
    FI
  OD
  lower(0)=lowerLen
  upper(0)=upperLen

  PrintF("lowercase letters:%E %S%E%E",lower)
  PrintF("uppercase letters:%E %S",upper)
RETURN
